### ISSUE TITLE
iOS Safari Extension

### ISSUE THREAD

**Issue by TanKot** [libredirect/libredirect#100]
This would be a very useful feature, if it were free unlike privacy redirect who has made it paid. This is a pretty big issue on iOS but would be fixed if you would do it.

**Comment by ManeraKai** [comment]
I don't have any iOS device and I don't know Swift. If someone can help though.

**Comment by TanKot** [comment]
Oh Ok.

**Comment by Mennaruuk** [comment]
Sadly, I find this highly unlikely. Apple went out of its way to be the first to destroy content blockers and redirectors on Safari for macOS and iOS. No webRequest API? That means when you type in Twitter.com/jack, Twitter actually gets pinged and knows you sent over a request to them, so thanks to Apple when you use an extension that redirects you to a privacy-respecting site, Safari will very happily pay the privacy-disrespecting site a visit before taking you over to Nitter.

that’s another worry I have for desktop because LibRedirector currently uses onBeforeRequest, and guess what, companies that have browser shares of 92% will gut onBeforeRequest. That’s Apple for you: one day they’ll make [an ad about privacy](https://piped.kavin.rocks/FbRUQRmvC4U), the next day they’ll gut the API without which privacy extensions won’t work well, and the day after they’ll make Facebook lose $10 billion by gutting personalized ads 🤕

**Comment by ManeraKai** [comment]
If there's no webRequest api then it's the same problem as with manifest v3 with the chrome web store: https://github.com/libredirect/libredirect/issues/45#issuecomment-1059010144

**Comment by Mennaruuk** [comment]
Yes you hit it right on the nail. Should this extension stay on the web store and switch to the less powerful Manifest v3? Difficult decision. Take a look at the Privacy Redirect Safari repo: there are [several issues](https://github.com/smmr-software/privacy-redirect-safari/issues?q=is%3Aissue) about sites not working bc of this, and the author has to constantly tell users about the limitations. I must mention that “Don’t be evil” Google will update Chrome in June ‘23 so that [all Manifest v2 extensions will stop working.](https://www.ghacks.net/2021/09/24/manifest-v2-chrome-extensions-will-stop-working-in-june-2023) Which is why I think it boils down to either switching to v3 or telling users to use Firefox/Brave and losing out on a good number of them. Ugh!!

**Comment by ManeraKai** [comment]
> there are [several issues](https://github.com/smmr-software/privacy-redirect-safari/issues?q=is%3Aissue) about sites not working bc of this, and the author has to constantly tell users about the limitations.

Yeah I see: https://github.com/smmr-software/privacy-redirect-safari/issues/10#issuecomment-963470001
I just can't change to v3 at all because of the problems you mentioned. Really sad.

I'll close this issue.

**Comment by Deagan** [comment]
I'd like this or something similar for iOS as well! Hopefully, once regulations force Apple to make their OS more open next year, Firefox/Chrome will have native functionality for Manifest v3.

**Comment by godly-devotion** [comment]
I ended up writing a userscript to redirect reddit and twitter (most used websites) to libreddit and nitter instances. Its slightly clunky but I guess this will do for now.

**Comment by ManeraKai** [comment]
@ftgjhf https://libredirect.github.io/faq.html#mv3

**Comment by ftgjhf** [comment]
> [@ftgjhf](https://github.com/ftgjhf) https://libredirect.github.io/faq.html#mv3

I see porting to MV3 [is planned](https://libredirect.github.io/faq.html#:~:text=We%20are%20planning,-to%20adopt%20Manifest) for Firefox because it provides the necessary APIs (I guess this is what the comment I linked was saying). Does Safari not provide these necessary APIs? Thanks!

**Comment by ManeraKai** [comment]
It wasn't supported before, and I don't think it will be in MV3: https://stackoverflow.com/a/73987583
