### ISSUE TITLE
Libredirect should not be the home page or default search engine

### ISSUE THREAD

**Issue by mostfunkyduck** [libredirect/libredirect#101]
It's a bad assumption that every user wants to proxy their traffic through the onion site of a browser extension and it's a bad assumption that every user wants that onion site as their homepage.  This is totally valid as an option, but it's pretty invasive for an extension to effectively hijack traffic with no warning, especially when that behavior isn't documented.  I assume this was done with good intentions, but it's a major red flag.

**Comment by ManeraKai** [comment]
Don't worry it's not an onion site, even Facebook can't make http://facebook.onion but instead has http://facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion
http://facebookcorewwwi.onion
It's just a fake url that I use to detect the Default Search Engine requests as I can't do that without it. I had two videos in the [matrix room](https://matrix.to/#/#libredirect:tokhmi.xyz) explaining what the hell is going on xD:
1. https://youtu.be/jkna60-nscI
2. https://youtu.be/ienPi1JkT_E

The browser warns you that the LibRedirect wants to be a Default Search Engine, though if this was a little bit getting into business, I'll try to inform the user of that in a different way.

**Comment by ManeraKai** [comment]
So... I've now deleted that notification and added an info message in the Search tab in the settings that states about having it as a default will be the best option if you wanna use the Search feature:
![image](https://user-images.githubusercontent.com/40805353/157658438-3f862780-f1a1-4379-8eba-3944af90b459.png)

**Comment by idotj** [comment]
I'm not sure if it is related with the search, but because I saw in the title of this issue "Home page" I would like to add my experience since I installed it.
In my case, every day that I click on my Home icon (at the main browser toolbar) Libredirect wants to change my default search page (that it is already a private search engine)
I didn't find any setting/option to stop doing this when I want to go to my homepage... (and I'm 100% sure that I unable the search option in the plugin)
*Please if you think that this issue is not related, I can copy my comment in a new one and remove this one.
Thanks for your great work!

**Comment by ManeraKai** [comment]
I fixed the homepage issue, you can reset it back to the default through here:
![image](https://user-images.githubusercontent.com/40805353/157666638-f2c41ac1-3d1e-4bc2-86a3-de8dbb743c38.png)
This (homepage) won't be in the extension anymore. I didn't know that it will behave like that.
