### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by stemy2** [libredirect/libredirect#117]
Hello,

The extension worked fine for a while, but now, none of the redirection i set is working. The addon and all redirection are enabled with at least one instance selected, but it is as if i didn't installed it at all.

**Comment by ManeraKai** [comment]
Try to reinstall it or reset the settings.

**Comment by catwithbanana** [comment]
This has happened to me a couple of times after updates; resetting the settings has fixed it every time.

**Comment by ManeraKai** [comment]
This is just weird. Idk why this is happening.

**Comment by Tallefer** [comment]
probably the same issue here, redirection stopped working on Firefox after the 1.5.2 version, I suspect the `*.init > await *.init` business here, despite it was aimed at chrome ofc, but can't think of anything else from that patch notes here:
[https://github.com/libredirect/libredirect/compare/v1.5.2...v1.5.3](https://github.com/libredirect/libredirect/compare/v1.5.2...v1.5.3)
tried 1.5.3, 1.5.5 and 1.5.6, did resetting and reinstalling addon, none of that helps. there's a chance of 1.5.5 working, but I saw it (kinda maybe) just once and can't reproduce it since

**Comment by catwithbanana** [comment]
It happened for me again after the latest update and resetting my settings again fixed it. Strange issue. I'm on Firefox.

**Comment by IronMaltese** [comment]
Same thing for me on Tor browser :/

**Comment by ManeraKai** [comment]
I wrote an answer to that in the [wiki](https://github.com/libredirect/libredirect/wiki/FAQ#its-not-working-at-all) as it seems that just updating LibRedirect causes a problem and there's no bugs in the code.
