### ISSUE TITLE
why fork?

### ISSUE THREAD

**Issue by dvikan** [libredirect/libredirect#129]
Just curious why this fork was created?

**Comment by EdwardLangdon** [comment]
Because Privacy Redirect was unmaintained. To say, No Updates or Fixes for a Long Time.

**Comment by IronMaltese** [comment]
For a lot of projects 3 months+ of unmaintained software is still usable, but especially since a lot of instances had been deprecated for the original extension, Privacy Redirect became basically unusable, not the mention all the frontends and features that are included in libredirect that aren't seen in Privacy Redirect make the old extension seem like a much smaller project compared to Libredirect

**Comment by dvikan** [comment]
thanks for answers! I suggest adding a note about this in the README at the very beginning. I think people get confused.
Keep up the good work.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/libredirect/issues/133
