### ISSUE TITLE
Add a Wiki

### ISSUE THREAD

**Issue by ManeraKai** [libredirect/libredirect#133]
- [ ] Why forking Privacy Redirect? How is LibRedirect better?
- [ ] Why all those permissions?
- [ ] Where the hell are those instances coming from?
- [ ] Why not using a single reputable instance?
- [ ] It's not working at all!

**Comment by EdwardLangdon** [comment]
So, For "Why Privacy Redirect ?"

Privacy Redirect seems unmaintained for about 3.5 months. And hasn't fixed issues reported by users or added New Features either.

So, We came into action and forked the project and improved it. That's it.

**Comment by EdwardLangdon** [comment]
For "Why not using a single reputable instance?"

Because randomness of Instance is made because if it is randomized there is a greater probability that Server loads are well Distributed and reduces the abuse of a particular Instance.

And a single Reputable instance is not meant to run for a long time because they need to maintain it like Hardware Upgrades, buying packages of Bandwith Traffic from the Hosting Provider. And it is mostly maintained by the Instance Owner (Hoster) money which mostly depends on donation also with his own Income. So, No Donation - No Instance. In that case, Randomzing it by default means - Load well Distributed. So, Less Traffic in every single Instance due to load Balancing and also Less Bandwith. In that case, It is a Win-Win Situation for Instances and Users.

That doesn't mean we always use Random Instances. We just do that by Default. You can use a particular one of your choice. You can do that too.

**Comment by ManeraKai** [comment]
This is a too long I think

**Comment by EdwardLangdon** [comment]
You are right though. I will shorten it in my Free time. And post it here again. 👍

**Comment by EdwardLangdon** [comment]
For **Why all those permissions ?**

The extension requires access to request data for **all websites** in order 
to intercept requests made to targeted services (Twitter, YouTube, Instagram ...) so that they may be redirected to the appropriate privacy 
respecting alternative, all other requests are ignored.

The extension also requires **local storage** permissions in order to store 
extension specific user preferences and settings.

**Comment by EdwardLangdon** [comment]
>You are right though. I will shorten it in my Free time. And post it here again. 👍

Because randomness of Instance is made because if it is randomized there is a greater probability that Server loads are well Distributed and reduces the abuse of a particular Instance.

And a single Reputable instance is not meant to run for a long time because they need to maintain it like Hardware Upgrades, buying packages of Bandwith Traffic from the Hosting Provider. So, Less Traffic in every single Instance due to load Balancing. It is a Win-Win Situation for Instances and Users.

That doesn't mean we always use Random Instances. We just do that by Default. You can use a particular one of your choice. You can do that too.

**Comment by EdwardLangdon** [comment]
>Where the hell are those instances coming from?

The Instances are fetched from the list maintained by the Official project maintainers. We Update the list via a Custom [Python Script](https://github.com/libredirect/libredirect/blob/master/src/instances/get_instances.py) which fetches changes such as addition and removal of Instances by the maintainers. And write the Data to a [.json file](https://github.com/libredirect/libredirect/blob/master/src/instances/data.json) which the extensions updates itself locally in the browser even if we stop maintaining Libredirect.

All Instances are updated this way. Only Piped Instances updated by ourselves customly due to technical limitations.

>It's not working at all!

@ManeraKai The above needs to be answered by you

I think I have helped you in answering most of the questions for the wiki.

**Comment by ManeraKai** [comment]
This is my try:
>  Why forking Privacy Redirect? How is LibRedirect better?

Privacy Redirect hasn't been maintained since 6/12/2021. Many instances are hard coded and should be removed as they became offline and many other should be added. Many PRs were just pending and waiting.
So we stepped in. This was the main reason of the fork. Later though, we started improving more and adding new features and frontends.

**Comment by ManeraKai** [comment]
> Where the hell are those instances coming from?

Every frontend project has a list of public instances. Ex: [Invidious' official instances list](https://api.invidious.io/), [Nitter's official instances list](https://github.com/zedeus/nitter/wiki/Instances). We fetch those lists using an automated [python script](https://github.com/libredirect/libredirect/blob/master/src/instances/get_instances.py). This python script gets triggered every 3 days. We don't intercept it at all. Those instances aren't our responsibility, they're the projects maintainers' responsibility.
Exceptions though with Piped as an example. We still only add the official instances but we add them manually as only the API links are [provided](https://github.com/TeamPiped/Piped/wiki/Instances). Mainly this is @EdwardLangdon's job.

**Comment by ManeraKai** [comment]
> It's not working at all!

This happens really weirdly after updating the instance. Just nothing at all works. Just try to reinstall the extension. If this didn't work, then open an [issue](https://github.com/libredirect/libredirect/issues).

**Comment by ManeraKai** [comment]
https://github.com/libredirect/libredirect/wiki/FAQ

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/160526787-15b2f97d-9a0e-4205-960c-325b500a825b.png)

Fix the Hyperlink for my Profile.

![image](https://user-images.githubusercontent.com/101938856/160526831-432a6bab-7105-43b3-ad46-a13a23f4b744.png)


Capitalize the 't'

That's it. Everything is well written. I think I need to write in the perspective of a developer instead of focusing on Normal People. Maybe, That's it.

If you fixed the above, Then Close this issue.

**Comment by ManeraKai** [comment]
Almost the ones that ask those things are devs or nerds and you can't just give plain answers. This won't convince them. I added your fixes and will close the issue
