### ISSUE TITLE
[Feature request] Clarify default

### ISSUE THREAD

**Issue by BirdInFire** [libredirect/libredirect#190]
When i actually go into the settings some services does not have tor version, but the select all is checked.

The feature is to let us unchecked this "master" switch even when no instance are present.
To be sure an instance will not be randomly selected after an update of instance (who add instance to a list who was empty before).

Possible alternative, change the default settings of this check-box from checked to unchecked (Same result).

**Comment by ManeraKai** [comment]
I think I should add a clarification note instead of disabling them.

**Comment by ManeraKai** [comment]
Normal behavior is as follows:
If you didn't touch the toggle-all button, it will add new fetched instances to the checklist.
If you touched it once, it won't add any new instances to the list.
This is it's default behavior from the beginning. I don't want to modify it because it will get complex really fast and this is a really rare scenario and will only might happen to Tor and I2P users.
