### ISSUE TITLE
Redirect Google Play Store to alternative

### ISSUE THREAD

**Issue by leethax666** [libredirect/libredirect#191]
ApkPure or some non-google frontend, it would be super helpful on ungoogled android

**Comment by ManeraKai** [comment]
I know Aurora can open those links right?

**Comment by EdwardLangdon** [comment]
@ManeraKai , You are right. But for that to open @leethax666 needs to go to the app info of Aurora Store, Then choose Set Defaults. There you need to choose. That's it. This is irrelevant to Libredirect, IMO. But I am keeping this open for your reply.

**Comment by m77e4t** [comment]
I think this topic is invalid.

On android browsers, you can only install extensions on firefox nightly/beta (gecko forks), kiwi browsers. On firefox beta builds the process is tedious to properly enable it. Since the extension is not on chrome web store, kiwi browser will also have problems. 

As a user you will come across google play store links in a browser and in an app. Libredirect has to do with browser, since it is an extension. But if you are on a degoogled android, you will probably not have google play store on your device. Then, the play store links in a browser will open in the google play store website. But, you cannot anonymously download apps from google play store website, making those google links useless.
Libredirect cannot control what happens in applications installed on your device, like if you come across play store link in whatsapp, telegram etc.

Also, I don't think there is such setting in Aurora store as Edward mentioned. Aurora store cannot open google play store links from a browser or whatspp and redirect it to aurora store. To do it, aurora store will need extra permission from android settings 'Display over other apps' and 'Open supported Links'. But, aurora store has open supported links via android settings, but it seems to limited inside the aurora app store itself and not able to intercept links like Libredirect does or Untrack Me app does.

Your best bet is to ask Untrack Me team https://www.f-droid.org/en/packages/app.fedilab.nitterizeme/

**Comment by ManeraKai** [comment]
https://user-images.githubusercontent.com/40805353/163437609-e67869ec-3e73-41e5-88d1-77bc74ae9a0c.mp4

**Comment by m77e4t** [comment]
I was wrong here then. For me, it does not work for some odd reason. All https://play.google.com links are given the option to open in my different browsers only.

But, I do see these settings in the android settings, like I said above.

![auroa store img 1](https://user-images.githubusercontent.com/96620334/163438822-fc4f272d-5c56-4829-9c91-8fd0aebb3184.jpg)

**Comment by EdwardLangdon** [comment]
Can you click on "Open Supported Links" and choose 'Always Allow' ?

Then do the same for Google Play store and choose 'Never'.

This will help you achieve what you want.

**Comment by m77e4t** [comment]
I have already done it for aurora store to 'Always open supported links' (play.google.com). I even changed it back and forth between 'Ask every time' and 'Always'. It does not work the way it is supposed to.

I do not have google play store on my device due to me being on a custom ROM with no gapps support.

It might be something related to my custom ROM. I will have to ask the custom ROM developer. Then, a future update of the ROM may solve it.

**Comment by EdwardLangdon** [comment]
So, Can we close this issue ?

**Comment by m77e4t** [comment]
The issue can be closed normally. The aurora store discussion was off-topic. The actual issue the user created is invalid itself.
