### ISSUE TITLE
Nitter embeds

### ISSUE THREAD

**Issue by catwithbanana** [libredirect/libredirect#20]
Nitter recently added embed functionality to their API. Tons of websites these days need Twitter embeds in order to be readable.

Could replacing Twitter embeds with Nitter embeds be incorporated into LibRedirect?

**Comment by ManeraKai** [comment]
Added a partial implementation here: https://github.com/libredirect/libredirect/commit/bdfa63acefd2744e2664f94d529b006ad336a611. What I mean by that is there's no error handling at the moment.

**Comment by catwithbanana** [comment]
> Added a partial implementation here: [bdfa63a](https://github.com/libredirect/libredirect/commit/bdfa63acefd2744e2664f94d529b006ad336a611). What I mean by that is there's no error handling at the moment.

Fantastic. Will it be included in the next release? I'll be happy to test it out & provide feedback once it's there.

**Comment by ManeraKai** [comment]
Yep, it will be in the next release, I think this night.
> I'll be happy to test it out & provide feedback once it's there.

I will really really appreciate that. I need some feedback on the extension.

**Comment by Victor239** [comment]
For long tweets the embed doesn't show all content:

![](https://i.imgur.com/F2lXfYD.png)

vs Twitter:

![](https://i.imgur.com/9i7J1bz.png)

Also it seems that many Nitter instances don't allow this embed feature:

![](https://i.imgur.com/bD5hHzA.png)

**Comment by Loki-L1130** [comment]
I think telling how you tested it would be great. So, that we can make and test it here.

**Comment by Victor239** [comment]
I was viewing tweets embedded on a private forum so it's not suitable for replication unfortunately.

**Comment by ManeraKai** [comment]
There are many forms of tweets. It's more of Nitter's support rather than the extension I think?

**Comment by catwithbanana** [comment]
I have found the same issue as Victor239 across several websites. Embedded tweets seem to always be the same height, meaning any longer tweets (or tweets with attached media) get cut off.

I don't mind this slight sacrifice to usability, personally, since I can still click through to see the full tweet, but it is there.

Also, Firefox still displays "Loading Tweet" on top of the Nitter embed even once it's loaded.

Here is an example page with an embed that gets cut off:
https://famiboards.com/threads/mario-kart-8-deluxe-booster-course-pass-paid-dlc-announced-48-courses-by-the-end-of-2023-25-free-with-nso-expansion.1911/

**Comment by ManeraKai** [comment]
> Here is an example page with an embed that gets cut off:
https://famiboards.com/threads/mario-kart-8-deluxe-booster-course-pass-paid-dlc-announced-48-courses-by-the-end-of-2023-25-free-with-nso-expansion.1911/

It's using a weird url: https://s9e.github.io/iframe/2/twitter.min.html#1491548842164064258light

**Comment by catwithbanana** [comment]
> > Here is an example page with an embed that gets cut off:
> > https://famiboards.com/threads/mario-kart-8-deluxe-booster-course-pass-paid-dlc-announced-48-courses-by-the-end-of-2023-25-free-with-nso-expansion.1911/
> 
> It's using a weird url: https://s9e.github.io/iframe/2/twitter.min.html#1491548842164064258light

Got it, thank you.

One more issue I've found. On some pages with embeds, such as this one:
https://mashable.com/article/best-funniest-tweets-week-february-18

Tweets don't get replaced; instead, having LibRedirect turned on causes all embedded elements to display a "Tweet may have been deleted" error message. When I turn off LibRedirect the embedded tweets show up as expected.

Please let me know if there's anything I can do to help troubleshoot this. This extension is absolutely killer, and I really apprecaite your hard work in creating and maintaining it!

**Comment by Loki-L1130** [comment]
> Tweets don't get replaced; instead, having LibRedirect turned on causes all embedded elements to display a "Tweet may have been deleted" error message. When I turn off LibRedirect the embedded tweets show up as expected.

You are right, It shows the error Message for me too.

**Comment by ManeraKai** [comment]
Maybe because some instances are outdated. Does refreshing the page multiple times to get an up to date instance help with that?

**Comment by catwithbanana** [comment]
> Maybe because some instances are outdated. Does refreshing the page multiple times to get an up to date instance help with that?


Unfortunately it does not. I have already limited my instances to just four that support embeds and work on other sites.

**Comment by CyberShadow** [comment]
Thank you. It doesn't seem to be working on https://www.reddit.com/live/18hnzysb1elcs/ with 1.4.3, not sure what might be wrong.

**Comment by ManeraKai** [comment]
> Thank you. It doesn't seem to be working on https://www.reddit.com/live/18hnzysb1elcs/ with 1.4.3, not sure what might be wrong.

?!

**Comment by CyberShadow** [comment]
The page has lots of Twitter embeds. Should they not be redirected to Nitter? Sorry if I misunderstood something.

**Comment by ManeraKai** [comment]
I'm sorry. It redirected me to a libreddit instance and it wasn't working. I didn't notice.

**Comment by ManeraKai** [comment]
@CyberShadow Uncheck all the instances and just use https://nttr.stream This one has it's http Headers right.
btw click on the date for the tweet to show. I think it's like that because the site is dynamic:
![image](https://user-images.githubusercontent.com/40805353/159366628-a8811b24-09f1-4121-a76a-8fac217f1d61.png)

**Comment by CyberShadow** [comment]
So if I understand correctly, there are two problems:
1. Most Nitter instances have a problem with their header configuration
2. libredirect doesn't support intercepting embeds which are created dynamically

> btw click on the date for the tweet to show.

Yep I've been doing that, thanks! But without the formatting, the inline ones are sometimes hard to read (links are glued to the text), so would be nice if it worked.

**Comment by ManeraKai** [comment]
More understanding of what is happening and I see that this "inline" text is a compatibility text. Like when your `<img`> doesn't load and you have the `alt` attribute that describes what the image is about: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_image_test
Try to change the `src` attribute value in the `<img>` element in that page and run it again. It will show you the `alt` text which is `Girl in a jacket`. Same story in that Reddit page.

Furthermore, if you pressed the `date` of the tweet. It won't open an `/embed` url. Instead it will open the whole page, e.g: https://nttr.stream/DefenceHQ/status/1506523823394406405?ref_src=twsrc%5Etfw
This furthers the idea of that it's a compatibility text. So, rather than pressing on it, open it in a new tab and it should work fine.

All of this is happening because the site doesn't use the old classic `<iframe>` with a simple url. I think it's using an API and that's how it can know if the browser is compatible or not to show that "inline" text. And I can't do much about it from my side. You should replicate the API. The same happened with the YouTube API. Context: https://github.com/libredirect/libredirect/issues/37

**Comment by CyberShadow** [comment]
I think the embedding is done via another third-party service, embed.ly. If JavaScript is completely turned off, then the page just has raw Twitter links (no tweet contents). I think embed.ly is what is creating the "placeholder text" and then tries to replace it with a Twitter embed.

I was also seeing the placeholder next because uMatrix is blocking Twitter. But, curiously, if I look at [the request log](https://user-images.githubusercontent.com/160894/159750276-8f886afb-b1be-4196-b243-bb1424c7d7e8.png), I'm seeing that it's loading the Nitter embed and all associated resources. I think embed.ly is rendering the embed (which is correctly being redirected to Nitter), however, it's waiting for some Twitter specific signal to display it. Maybe this signal is not implemented in Nitter.

Inspecting the redditmedia.com iframe, I see:

![image](https://user-images.githubusercontent.com/160894/159751158-9e855f54-d0a7-40bc-b52f-1301ca4a6b3b.png)

If I manually unhide the twitter.com iframe, then I do see the Nitter embed.

So, it seems libredirect is working correctly, but there might be a little bit missing on the Nitter side.

**Comment by catwithbanana** [comment]
@CyberShadow Could you post about this issue on the [nitter github?](https://github.com/zedeus/nitter) I would love to see this fixed but I am not smart enough to transfer what you wrote to what they need to hear.

Thanks again to @ManeraKai for your hard work on this amazing extension.

**Comment by catwithbanana** [comment]
Also, does the fix for this issue:

> One more issue I've found. On some pages with embeds, such as this one: https://mashable.com/article/best-funniest-tweets-week-february-18
> 
> Tweets don't get replaced; instead, having LibRedirect turned on causes all embedded elements to display a "Tweet may have been deleted" error message. When I turn off LibRedirect the embedded tweets show up as expected.

Also need to happen on the Nitter side of things? 

I am not a programmer, so I can't claim that I 100% understand everything in this thread or how this issue can be fixed. I want to be sure I follow up wherever follow-up is necessary to make Nitter embeds compatible on more sites, but I'm not sure where to go next. Thank you!

**Comment by CyberShadow** [comment]
Alright, I created an issue after a bit more research.

https://github.com/zedeus/nitter/issues/586

> Also, does the fix for this issue:

It seems to be the exact same problem as the Reddit Live one.

**Comment by ManeraKai** [comment]
btw till now `widget.js` is being blocked by libredirect or redirected you can say. I'll disable redirection for scripts

**Comment by catwithbanana** [comment]
> @ManeraKai In [zedeus/nitter#586](https://github.com/zedeus/nitter/issues/586) it was suggested than libredirect finds and replaces `<blockquote class="twitter-tweet">` tags with Nitter embeds. Would that make sense to you?

Is there any possibility of this getting implemented? I wonder if this implementation may also help Issue #183 which has persisted for several days now.

**Comment by ManeraKai** [comment]
This will only work for that site. Won't work on the others

**Comment by CyberShadow** [comment]
It should work for at least the two example websites in https://github.com/zedeus/nitter/issues/586, no?
