### ISSUE TITLE
Libredirect creating Unnecessary Cookies

### ISSUE THREAD

**Issue by EdwardLangdon** [libredirect/libredirect#204]
![image](https://user-images.githubusercontent.com/101938856/163759483-d7e8f1ce-7b8f-46b4-856b-b8b8fa21c225.png)
When you see the above image. Libredirect creates a `.onion` cookies for TOR protocol even though I use only Normal Protocols.

**Comment by m77e4t** [comment]
Same thing happens to me. I was going to create an issue for this. 

Sometimes, I even see non-TOR instance cookies in the tab. I will verify it again, if the non-TOR cookies are due to the above issue or are they enabled by me.

**Comment by vairag22** [comment]
It starts creating cookies as soon as I open the browser.

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/165671925-74d97b8a-109a-4568-b1ad-459ceee91ee5.png)

The Issue seems to be present in Microsoft Edge too.

**Comment by vairag22** [comment]
Yeah, this happens if you have toggled **Enable Custom Settings** option. As soon as you open your browser Libredirect will start checking if cookies with required settings exist, if not then it'll start creating/modifying those cookies.

If your browser is set to clear cookies on exit then the extension will start creating cookies everytime the browser is launched. This results in an abrupt spike in CPU and RAM usage. Browser may start lagging and some sites might not load correctly for a minute or so, depends on your hardware specs. See issue #219.

**Ideally, cookie creation/modification for a website must be triggered only when user is redirected to it.**

A quick fix that I've been using is to manually untoggle all instances that I don't use: https + cloudflare, i2p and tor. Cookies are still created at launch but only for a subset of instances. Getting significantly better performance and no wait screens.

**Comment by vairag22** [comment]
Yeah, this happens if you have toggled **Enable Custom Settings** option. As soon as you open your browser Libredirect will start checking if cookies with required settings exist, if not then it'll start creating/modifying those cookies.

If your browser is set to clear cookies on exit then the extension will start creating cookies everytime the browser is launched. This results in an abrupt spike in CPU and RAM usage. Browser may start lagging and some sites might not load correctly for a minute or so, depends on your hardware specs. See issue #219.

**Ideally, cookie creation/modification for a website must be triggered only when user is redirected to it.**

A quick fix that I've been using is to manually untoggle the instances that I don't use: https + cloudflare, i2p and tor. Cookies are still created at launch but only for a subset of instances. Getting significantly better performance and no wait screens.

**Comment by EdwardLangdon** [comment]
I know that, But the Thing is I don't use TOR Instances just normal so it shouldn't be here. You get it - @vairag22 ?

**Comment by ManeraKai** [comment]
Fixed it. Now LR will only make cookies for the desired protocol.

**Comment by vairag22** [comment]
> I know that, But the Thing is I don't use TOR Instances just normal so it shouldn't be here. You get it - @vairag22 ?

I recommended disabling tor, i2p, etc. instances just as a temporary solution until the bug is properly fixed. I think was clear enough.

**Comment by vairag22** [comment]
> I know that, But the Thing is I don't use TOR Instances just normal so it shouldn't be here. You get it - @vairag22 ?

I recommended disabling tor, i2p, etc. instances only as a temporary solution until the bug is properly fixed.

**Comment by m77e4t** [comment]
https://user-images.githubusercontent.com/96620334/166293057-909ede28-81e8-4777-863e-4dc4f23ee612.mp4

Over 100 cookies just after opening firefox browser. 

Tor/I2p is disabled for all instances/protocols. 
"Enable Custom Settings (will use cookies)" is disabled.

**Comment by vairag22** [comment]
Fixed in commit [2b4ea71](https://github.com/libredirect/libredirect/commit/2b4ea71e78309a144c2eb8d5534ae99f665e804d), will be included in the next release.

Quick Fix: Manually disable each and every instance for TOR, I2P, alternative frontends, and ones you do not use.

**Comment by EdwardLangdon** [comment]
> Fixed in commit [2b4ea71](https://github.com/libredirect/libredirect/commit/2b4ea71e78309a144c2eb8d5534ae99f665e804d), will be included in the next release.
> 
> Quick Fix: Manually disable each and every instance for TOR, I2P, alternative frontends, and ones you do not use.

You mean to uncheck Toggle All button ?

**Comment by vairag22** [comment]
For some protocols and frontends, yes. For others, no. Left that to the common sense of the user.

**Comment by EdwardLangdon** [comment]
I think it's unnecessary after the New Update is released.

**Comment by vairag22** [comment]
I agree. But until it is released any working solution is useful, no?

**Comment by EdwardLangdon** [comment]
I don't know, It isn't much of a Concern for me as of now, May be for others.
