### ISSUE TITLE
Checking instances online status so you don't redirect to dead/currently offline instances

### ISSUE THREAD

**Issue by sonalder-darlene** [libredirect/libredirect#225]
I love this extension but I'm often redirect to unreachable instances. 
It would be nice to have a way for the extension to check every hour, every 12 hours or every time you open your browser all the selected instances, if some are unreachable LibRedirect could temporarily disable them so you only get the one that are online and never again face a dead link.

I don't know how to make this but it would be a nice feature to have.

**Comment by ManeraKai** [comment]
Auto redirect off offline instances works nicely with this. Doesn't it?

**Comment by ManeraKai** [comment]
Hello?

**Comment by sonalder-darlene** [comment]
Oh I've didn't tried this feature, feel dumb now.
Why isn't on by default ?

**Comment by ManeraKai** [comment]
It's not as it did go crazy multiple times. I've now restricted it a lot and even limited the number of auto redirections before stopping.
I kept it off by default just to be safe and for security reasons.

**Comment by graynk** [comment]
Sorry to bump an old thread, but does this feature actually work? I have this enabled, and I end up seeing dead instances constantly on Firefox

**Comment by ManeraKai** [comment]
Are those instances "offline" or just redirect to ads sites and such?

**Comment by graynk** [comment]
Offline
<img width="919" alt="image" src="https://user-images.githubusercontent.com/3626328/200114557-9e93da49-c34a-4936-9374-e5b7124d8635.png">

**Comment by ManeraKai** [comment]
This instance isn't on the list though. LibRedirect can't know if this is a libreddit instance or not

**Comment by graynk** [comment]
Then I'm even more confused than I was initially, because I've just pressed a search result in Google:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/3626328/200114682-317a508c-5ed7-43fa-96e4-1de9223b355b.png">

I don't have any other redirect extensions, this instance doesn't seem to be on the list either, why am I getting redirected there then?
<img width="937" alt="image" src="https://user-images.githubusercontent.com/3626328/200114721-64126949-f672-4087-a6a5-d61b1468e270.png">

**Comment by ManeraKai** [comment]
Just to be sure, you enabled this setting specifically right?
![image](https://user-images.githubusercontent.com/40805353/200114895-7031fa54-cab0-487b-92c0-37463c3700d6.png)

**Comment by graynk** [comment]
Yes, this is the setting that I'm talking about, and it's enabled. And I also _don't_ see the instances from screenshots in the list of Reddit instances

**Comment by ManeraKai** [comment]
Then they seem to be there but hidden in the settings, export your settings and search in the exported file for those instances names.

**Comment by graynk** [comment]
Ah, OK, I see them now. They both seem to be in the `clearnet` section, and `fallback to clearnet` toggle is enabled (and I can't disable it?)

So that explains why I see them - I guess it can't find any living instances, then falls back to one of the clearnet ones, and they just so happen to be dead as well?

Not sure why it fails to find living instances though - if I click on five different results in Google search - I then have 5 different tabs with 5 different instances, some of them clearly alive, others - dead. Would it be possible to implement a setting that would allow the extension to remember the last successfully accessed instance and default to that?

**Comment by ManeraKai** [comment]
Just try to update the instances list and see.

**Comment by graynk** [comment]
Updated, seems better now. In this case another possible feature request is the "auto-update instances" toggle, I guess :)

Thank you for your work and for extremely fast responses!

**Comment by ManeraKai** [comment]
I think we should have that option. Open a new issue for it plz.
