### ISSUE TITLE
add libremdb and quetre

### ISSUE THREAD

**Issue by paul38752** [libredirect/libredirect#230]
https://github.com/zyachel/libremdb
https://github.com/zyachel/quetre

**Comment by EdwardLangdon** [comment]
I never though that there are alternatives to IMdb and Quora.

**Comment by EdwardLangdon** [comment]
There is no Instances as far as I know. So, We need to wait. Until there is an Instance available.

**Comment by ManeraKai** [comment]
@EdwardLangdon There are but just one instance. It's the main website.

libremdb example: https://libremdb.herokuapp.com/title/tt0133093/
Quetre example: https://quetre.herokuapp.com/How-does-the-Z-boson-decay

**Comment by vairag22** [comment]
Is that a problem? I remember when Proxitok was added to LR only main website was available. Second instance was added much later.

**Comment by ManeraKai** [comment]
What's the problem?

**Comment by vairag22** [comment]
m> @EdwardLangdon There are but just one instance. They're the main websites.

Adding LibremDb and Quetre to LR

**Comment by ManeraKai** [comment]
no there isn't, yeah it can start off as just one instance. We're here to support projects like this.

**Comment by EdwardLangdon** [comment]
I thought that It was just the Homepage as there is no Search Bar, Settings,etc - Nothing. 

But, One Thing is I cannot click in Actor's Profiles like in IMdb. Personal Opinion though.


But Quetre's UI is very much better than Quora.

**Comment by paul38752** [comment]
The search bar is on todo.

**Comment by zyachel** [comment]
Thank you all for taking interest in my ambitious projects. I really appreciate that. :)

As for the missing functionalities, I'm quite occupied with exams and hence made the websites just usable enough for now.  
But I will definitely make at least Quetre feature-complete as soon as I get time. It is more important since Quora is totally unusable without JavaScript, sometimes has answers people might be looking for, and is in general resource heavy.      
IMDb, on the other hand, has many more routes, is still usable(to some extent) without JavaScript, and hence libremdb will remain incomplete for some more time(though I will not abandon it).  

Maybe it is a good idea to not add these front-ends just yet(especially libremdb), as lack of some frequently used routes might make some users uncomfortable, just as @EdwardLangdon describes.  

---

PS: I was originally searching for my repo and this discussion came up in the search results :p

**Comment by EdwardLangdon** [comment]
Oh, Great to know. But are they available at the Official Project Repo's List ?

**Comment by mdb571** [comment]
@EdwardLangdon yes they are listed in their respective project repos
https://github.com/zyachel/quetre#instances
https://github.com/zyachel/libremdb#instances

**Comment by EdwardLangdon** [comment]
Great to know. We will work on this.

**Comment by ManeraKai** [comment]
Added Quetre, but I'll wait some more time for libremdb.

**Comment by ManeraKai** [comment]
Added Libremdb, I don't know but we'll take time to release and I won't delay it for the release after the next one.
