### ISSUE TITLE
Make guidelines for addition of new frontends

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#254]
Some people are getting wrong ideas about LR because certain frontends were added that do not enhance privacy. So I suggest we should make some guidelines regarding addition of new frontends.

**Comment by IronMaltese** [comment]
> Some people are getting wrong ideas about LR because certain frontends were added that do not enhance privacy. So I suggest we should make some guidelines regarding addition of new frontends.

1. All requests must be proxied

2. Open Source

3. Enhances privacy over main site

4. Has a working instance

**Comment by ManeraKai** [comment]
Having it proxying every thing is important but all this can be mitigated using VPN or Tor. The main thing is to make JavaScript opensource or not required.

**Comment by m77e4t** [comment]
I would say the main thing is 'privacy focused' redirection compared to other points.

Something like google->starpage/whoogle/searx instead of starpage->whoogle/searx since starpage is already privacy friendly, so there is no need to redirect startpage to searx.

For those who want it, they may do it via DNS redirection, or via redirector extension etc.

**Comment by EdwardLangdon** [comment]
> is to make JavaScript opensource or not required.

Or Completely HTML like Invidious, Libreddit and Nitter

**Comment by ManeraKai** [comment]
There in the site now: https://libredirect.github.io/faq.html#suggest_frontend

**Comment by IronMaltese** [comment]
The site looks great! 🐕🐕🐕🐕🐕🐕
