### ISSUE TITLE
Feature Request: Test Latency of Custom Instances

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#265]
I appreciate the option to test latency of pre-registered domains like vid.puffyan.us, but it would be nice to have this feature for custom instances too. For example, iteroni.com is the instance I default to usually.

**Comment by ManeraKai** [comment]
It's really unnecessary since the purpose of it is just for helping the user know what the best instances are by latency. Like if you use a custom one you already know more info about it. Same way it doesn't have the cloudflare warning as you should know this already when adding a custom instance.

This is my philosophy.
