### ISSUE TITLE
Redirects stopped working after update

### ISSUE THREAD

**Issue by wrhou** [libredirect/libredirect#293]
Went to Youtube just now and it didn't redirect me to any of the Piped instances I specified. Same with twitter. Checked Libredirect settings just to see if they were reset, they're still the same as before the update as far as I can tell.

**Comment by ManeraKai** [comment]
Reset. I'll keep this issue opened for other people too.

**Comment by Sargastic** [comment]
Same problem here (guess a lot of other people will have it). Resetting settings did the trick.

**Comment by EdwardLangdon** [comment]
>Resetting settings did the trick.

It is because v1.7 & 2.0 are incompatible. So, It wasn't working. After you reset, It's just v2.0 settings. So, It's working as expected.

**Comment by sxe** [comment]
Can we please get a notification after an update if this is ever happening again? 
It's not the first time either and mildly frustrating to not know what's going on. Besides that, setting up everything again, isn't the most fun either.

**Comment by ManeraKai** [comment]
> Can we please get a notification after an update if this is ever happening again?

We're planning to add a popup warning of an automatic settings reset after every Major release.

> Besides that, setting up everything again, isn't the most fun either.

Removing the front ends settings from the settings page reduces the amount of settings till the point of just redirection settings and this is maintainable.

**Comment by sxe** [comment]
> Removing the front ends settings from the settings page reduces the amount of settings till the point of just redirection settings and this is maintainable.

Not sure what you are telling me here to be honest.
I noticed there are no more instance settings at all. Is that supposed to happen? Is there no way anymore to, for example, set a specific setting for piped that is automatically applied to all instances?

**Comment by ManeraKai** [comment]
No it's still there but got better: https://libredirect.github.io/faq.html#what_is_unify_settings

**Comment by sxe** [comment]
Ah cool, is that literally setting a cookie for each instance? I am asking cause my browser deletes cookies after shut down and that would delete those settings as well. So I would have to exclude each instances separately from deleting the cookies. In 1.7 it was super comfortable to not have to worry about cookies at all.

**Comment by ManeraKai** [comment]
There's a mechanism for that. It doesn't just copy the settings, it also stores them in LibRedirect's settings. So even if you cleared the cookies and relaunched your browser, they will be rewritten again. We also did this mechanism for Tor and incognito mode but at the moment they're having some problems. though for regular browsers, it will work correctly.

All those changes and this one specifically made it incompatible. I also rewrote it almost completely and cleaned the code, you can check the change log here: https://github.com/libredirect/libredirect/releases/tag/v2.0.0

You really can't make it backwards compatible after all those changes.

**Comment by sxe** [comment]
Hey yeah thx all good. I read the changelog already but it wasn't really clear to me what happened form reading it.

Maybe a short section like **What changed** would be good when big changes like this happen in the future. To explain a bit more straight forward the implications for the normal user.

Anyways, thx for all the work you are doing. Love the addon.

**Comment by ManeraKai** [comment]
> Maybe a short section like What changed would be good when big changes like this happen in the future. To explain a bit more straight forward the implications for the normal user.

@EdwardLangdon and me will start writing more informative change logs with links to every issue. It will turn out good.

> Anyways, thx for all the work you are doing. Love the addon.

❤️

**Comment by PTsuarez** [comment]
I've noticed another issue with the most recent update. 

I only want to have youtube redirect for embedded videos only which is the option that I enabled and worked perfectly before but now it doesn't it always redirects completely instead of just for embedded videos.

**Comment by owintwist** [comment]
If I understand well…

You made a change in how settings are stored. Changes who gonna break compatibility and **made the extension not working anymore.**  
And you knew it.

But you **didn't** plan to detect old settings and migrate them to the new settings system, so it would be seamless for users.

Instead, you roll out changes and expect **users to do a manual operation** (!). And that operation is basically to wipe all settings out (!).

But, without asking them to do so (!). Because you didn't make the notification tool you plan to. 

You just put this major information in the changelog and a kept-open ticket on github, like everyone known wtf are those things.

**Comment by EdwardLangdon** [comment]
@owintwist I understand your anger and concern. We will try to do better next time. This is the first time we are working on a project like this. We aren't a Company that can take care of all things, Just people trying to help other people in our free time and out of passion.

>And that operation is basically to wipe all settings out (!).

I think you could exported and then reset and tried resetting.

> and a kept-open ticket on github

We opened the ticket to keep a log of that issue as soon as many people asked about the new changes.

>that's not the first time you do so

I am not sure about this.

**Comment by ManeraKai** [comment]
@PTsuarez fixed your problem 👍️

**Comment by 154pinkchairs** [comment]
Embedded videos are defaulting to YT (some content is loaded from Invidious, but generally I need to allow YT's garbage through uMatrix). I'd like to upload screenshots, but GH throws some unknown error atm.

**Comment by ManeraKai** [comment]
@154pinkchairs I fixed this bug.

**Comment by mpeter50** [comment]
I've read that you want to just reset the settings of users without question starting from the next version, if they are coming from 1.x.x. I wouldn't recommend doing that, because the user will lose what instances they have enabled/disabled. Personally I have put some time into selecting which ones I want to use and don't want to repeat it if not necessary.

Instead, there could be 2 buttons on the upcoming warning page:
- export settings, or at least export enabled instance list into a human readable format
- reset settings

Also, I would recommend releasing the version with the warning page as soon as possible, because most people won't come to github, but will just remove the extension because it's broken.

Overall the extension looked pretty good so I switched from Privacy Redirect, but changes like these make me reconsider that decision. PR just worked, and this one throws my preferences in the trash bin.

**Comment by EdwardLangdon** [comment]
Well, We are busy. @mpeter50 , We will try to do so within this month.

**Comment by mpeter50** [comment]
By the way, if someone hasn't yet deleted the settings, and they are on version 2.0.0, it's still possible to recover your enabled instances, and take a look at your old settings, by following these instructions:
1. Type `about:debugging` into the URL bar
2. Click on "This Firefox" on the left side
![image](https://user-images.githubusercontent.com/83356418/171403236-e9da5b3a-1dd7-4bd2-92d4-fca704eace2c.png)
3. Scroll down until you find the card for LibRedirect, and click "Inspect"
![image](https://user-images.githubusercontent.com/83356418/171408559-e1b06a1e-8608-40b5-b58a-1583b8ae452e.png)

After that, the old settings are visible in the table on the right. Column width can be adjusted by dragging a column separator.
4. In the new browser tab, select the "Storage" tab
5. On the left side open the dropdown for "Extension Storage" and click on the item that is revealed.
![image](https://user-images.githubusercontent.com/83356418/171404026-8598ac32-830c-412e-95a2-92cb5b64aabf.png)

**Comment by ManeraKai** [comment]
There's also a problem with updating the instances list. Like imagine if your selected instance got removed from the official list, it will just disappear from your selection
Same when adding more instance:
If you've selected all the instances but unchecked one or two, does that mean that you will accept the new instances from the new updated list?

Till now if you press update instances, your selection will be reset due to those factors. Idk how to implement it in a more practical way.

**Comment by EdwardLangdon** [comment]
@owintwist May I know why was the ping for and what do you like to tell here by the facepalm emoji ?

>I understand that, it happens with everyone, but please be more careful. Unless you have to hurry with an update, you can test it and polish it until needed.

Well, We tested the addon a lot, You can even visit the Libredirect Matrix room. You can see my matrix ID and Manerakai's discussing and testing the Newer one.

The One wrong thing is, We didn't check for Compatibility with older version as it was new thing, I didn't check actually.

>Also, sorry if I seemed to be harsh, I didn't intend so.

It's okay, Don't be.

**Comment by owintwist** [comment]
> @owintwist May I know why was the ping for and what do you like to tell here by the facepalm emoji ?
Absolutely not. 
I was only here to pointing you **how disorganisation and not thinking in the user perspective is wrong and may lead to loosing lots of users** and was open to help. 
Not debating about why I think your answer was _palmfaceable_.

**Comment by owintwist** [comment]
> @owintwist May I know why was the ping for and what do you like to tell here by the facepalm emoji ?

Absolutely not. 
I was only here to pointing you **how disorganisation and not thinking in the user perspective is wrong and may lead to loosing lots of users** and was open to help. 
Not debating about why I think your answer was _palmfaceable_.

**Comment by mpeter50** [comment]
@ManeraKai
> Till now if you press update instances, your selection will be reset due to those factors. Idk how to implement it in a more practical way.

Hmm, I didn't know this. I think it would be useful to have a warning box near the instance selectors that selection is reset on updating the instance list, while it works that way.

On how to handle this better I have a few ideas, but I don't know how much work would it be to make it work this way.

For whether to automatically allow newly added instances:
I think there could be a toggle button for this, one for every service type (so separately for youtube, for reddit, for medium, etc).
I see that you store the list of enabled instances under a separate key (e.g. `invidiousNormalRedirectsChecks`).
When updating the instance list, the contents of this key would be kept, and new instances would be added to it if the toggle is set to add new instances automatically.
The addon would know if an instance is new if it is included in the newly downloaded list but isn't in the old list (so this would probably need to be decided in the update procedure, before overwriting the instance list with the new one).

For the situation when instances are removed:
The content of the enabled instance list is still kept. If a removed instance was enabled, it is not removed from the enabled instance list, but automatic redirection would only happen to instances which are
- both on the enabled instance list AND the downloaded instance list
- OR on the custom instance list.

On the long term this could lead to very long enabled instance lists because of the enabled-but-now-unknown instances, but the UI could show them dimmed out in the main instance list (like [this](https://user-images.githubusercontent.com/83356418/171995934-46b01863-f44d-404a-b9f7-85e9bc37233e.png)), with 2 active buttons, so it is manageable: delete, move to custom instance list.
This way the user could see if one of their enabled instances was removed from your list, and decide whether they still want to use it or not.

What do you think?

**Comment by Dyras** [comment]
I think mpeter50's suggestion to have a toggle next to every instance type would be a good idea. It caught me a bit off guard that the instances aren't updated automagically, ever. 

I think automagically updating the instance list every x day, with an opt-out feature for every instance type would be the best solution. I think there's a minority of people that opt-out of certain instances, so for the majority of people automatic updates would be a good thing, IMO. For the power users, there's a way to opt-out if they want their own list for whatever reason.

**Comment by ManeraKai** [comment]
I think I'll start implementing this suggestion in 2.2, I'll release 2.1 after some days.

**Comment by wadbr** [comment]
I am having this issue with twitter only, been happening for 2 updates I think (I reset my settings both times). Tried selecting a single instance, using tor, selecting all instances etc but nothing is working so far.

**Comment by ManeraKai** [comment]
@wadbr I'll see whats wrong.

@Dyras he already did two times.

**Comment by ManeraKai** [comment]
@mpeter50 Can you open a separate issue and we'll complete from there? I'll close this one.

**Comment by mpeter50** [comment]
Sure! I've made the above new issue
