### ISSUE TITLE
Bring back instance settings

### ISSUE THREAD

**Issue by vairag22** [libredirect/libredirect#296]
Why were instance settings removed? They worked fine and were quite useful.

**Comment by vairag22** [comment]
Okay so I read the v2.0.0 Changelog, 
> The setting page settings for every frontend has been removed in the favor of Unify Settings

Figured out how to use "Unify Settings", but personally I do not like it. Changing settings has become too much work for me; I've to go to an instance, put it on cookie exception list, enable JavaScript (for some instances), change settings, "unify" them, disable JavaScript, and then remove the instance from cookie exception list.

A suggestion: Replace Unify Settings icon. [Current icon](https://www.flaticon.com/premium-icon/link_3018420?term=link&page=1&position=17&page=1&position=17&related_id=3018420&origin=style) | [Suggested icon](https://www.flaticon.com/free-icon/merge_3580192?term=merge&page=1&position=7&page=1&position=7&related_id=3580192&origin=tag#)

**Comment by EdwardLangdon** [comment]
Well, I asked manerakai but he wanted to keep things simple. Maybe if many people ask he might bring it. But, You need to wait because many are complaining for breaking Libredirect in v2.0 while shifting from v1.7 to v2.0. 

So, We will plan it out and will do things without any breakage if we were gonna do it.

But Vairag, I understand and agree with you. Old settings was much better and easy to use.

Maybe @ManeraKai If you were gonna bring it back, How about hiding it under a dropdown menu after bringing it to keep things clean.

Mostly kai won't bring back as he had done a lot of work of unifying. If you want old thing back make a Campaign. This line is just my Opinion.

**Comment by ManeraKai** [comment]
> A suggestion: Replace Unify Settings icon. [Current icon](https://www.flaticon.com/premium-icon/link_3018420?term=link&page=1&position=17&page=1&position=17&related_id=3018420&origin=style) | [Suggested icon](https://www.flaticon.com/free-icon/merge_3580192?term=merge&page=1&position=7&page=1&position=7&related_id=3580192&origin=tag#)

In the future it will be almost a link as I'll make one instance as the parent one and every other instance update their settings even without pressing the button. So it will be like a link more than a Unify but it's an interesting icon.
