### ISSUE TITLE
Tor links support

### ISSUE THREAD

**Issue by Latrolage** [libredirect/libredirect#32]
In the new UI, batch URL importing was removed.

**Comment by ManeraKai** [comment]
you mean a whole ready list file?

**Comment by Latrolage** [comment]
Doesn't have to be a file, it can just be a text area to paste. With each entry separated either line by line, or by commas like before

**Comment by ManeraKai** [comment]
Is this feature really needed? I've removed it because almost no one will add a whole custom list of servers. Usually he just has his own server that he wants to add. Even if he had a custom list, he will still require an IDE at least to remove the `""` from that list if it was a JSON file and separated it with commas and all that. It will be just like adding each instance then pressing Enter to register it in the current extension design. You can press Enter rather than the button to register the instance.

**Comment by Latrolage** [comment]
I wanted it before to add the onion sites to the extension which was quite tedious. I the direct solution to that would be to add the onion sites by default to the extension. 

Maybe under an "onion sites" subsection within each alternative service or something

**Comment by ManeraKai** [comment]
I see, onions sites are in the extension but we didn't implement them yet: We'll do that soon 👍
![image](https://user-images.githubusercontent.com/40805353/153714927-7c41b1cc-0144-4923-93d9-7180e226952c.png)

**Comment by ManeraKai** [comment]
I think you weren't able to install it on Tor don't you?

**Comment by Latrolage** [comment]
You can install any firefox plugin on tor, its just not recommended by most. 

Also brave browser can access onion links (not that i use it) so it could be helpful there

**Comment by ManeraKai** [comment]
I was able to install it at the end. You should enable it in `Private Mode` for it to show though.

**Comment by ManeraKai** [comment]
The new release has tor support for some frontends. Though not all of them yet.

**Comment by ManeraKai** [comment]
I think we've finished @Latrolage
