### ISSUE TITLE
Can't Update Invidious Settings with Unify.

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#323]
I'm trying to change the default video quality from DASH 480 to Small, and it usually saves that quality option for that instance in normal browsing, but I can't unify the change across other instances or private browsing. 

Unify just isn't working.

**Comment by MintMain21** [comment]
Update: I just manually deleted all my invidious cookies and then started from scratch. So far so good. Will keep this open if anyone wants to add anything.

**Comment by EdwardLangdon** [comment]
@MintMain21 You mean it's working again ?

**Comment by MintMain21** [comment]
After I manually deleted the cookies, yes.

**Comment by EdwardLangdon** [comment]
Good to hear, Will close this issue later if there aren't any issues spotted by other users.

**Comment by ManeraKai** [comment]
I think I should remove any existing cookies that have the same value so there will be no overlapping. I did face the same issue while debugging the extension

**Comment by ManeraKai** [comment]
Hopefully it will be fixed by this, btw all this happened because I added the `secure` key so it though it didn't replace the old cookies rather made a new one.

**Comment by rezad1393** [comment]
I had an issue that odysee and quara redirect wouldn't work.
so I reset the setting .
now they work
but now invidious setting don't stick.
every time I restart browser they are gone.
I think because unify setting doesn't work.
why that is?

**Comment by rezad1393** [comment]
something even more weird.
in version one of addon I had set firefox to remove coockies upon restart.
so yewtu.be (invidious site) would get its setting from the addon .
after update of addon  I used unify setting and it worked.
then quera didnt redirect so I reset the setting and then set yewtu.be setting and allowed it to keep setting as cookie.
but unfiy setting didnt work.
now my issue is that somehow the addon resets the yewtu.be setting.
so the unify kinda works but not as my set setting.

**Comment by rezad1393** [comment]
I cant track it.
because it usually happens with firefox restart.
I have added yewtu.be to coockie allow list.
but when I restart the firefox and then open a youtube page it seems to use 720p video instead of dash.
when I go to yew setting page I see that it is set and dash and when I click save at the bottom with no change , I get the dash page.
after saving the setting , if I open a new tab and then open the same video in its youtube link, so that redirect happens, again I get 720p video in yewtu.be.
it seems that this added does its thing when redirect happens right?
this is the messages of werbdev attached. I see one with PREFS error so maybe that's it?
[console-export-2022-7-2_8-38-25.txt](https://github.com/libredirect/libredirect/files/9032398/console-export-2022-7-2_8-38-25.txt)

**Comment by ManeraKai** [comment]
>  it seems that this added does its thing when redirect happens right?

Nope. Redirecting doesn't trigger writing cookies for LR.

**Comment by rezad1393** [comment]
> > it seems that this added does its thing when redirect happens right?
> 
> Nope. Redirecting doesn't trigger writing cookies for LR.

I don't understand.
then when does the addon writes the cookies?
because when I restart firefox and open yewtu.be page directly its setting are like the last time I saved from its setting page and it is played in dash.
but when I open a youtube link and it gets redirected to the yewtu.be page the page uses 720p non-dash one.

also now I notices that after the redirect if I open the invidious page directly again, then the video is in dash again.
so maybe it doesn't write the cookies at redirect but whatever it happens causes the video to play at non-dash.
In another issue I opened youtube embedded videos are loaded with non-dash and consume bandwidth.
so what ever is happening it is at the redirect.

**Comment by ManeraKai** [comment]
It also happens with my invidious instance. If I visited it normally cookies are working. If I visited youtube.com and got redirected, even the login credentials are not working until I refresh the page.
It has something to do with security policy:
![image](https://user-images.githubusercontent.com/40805353/176988808-08b1c7f3-c0bb-4096-b429-bf52e6fa1507.png)
