### ISSUE TITLE
Extension redirects Google My Maps maps

### ISSUE THREAD

**Issue by Elaborendum** [libredirect/libredirect#328]
Maps from Google My Maps are user generated through Google, so they can't be accessed through OpenStreetMap. The extension currently just opens the OpenStreetMap equivalent for one of the nodes of the GMM map.

Here's an example: https://www.google.com/maps/d/viewer?mid=1e1vwtSkJf3g26_Mh5EC7xdFz5ayqDN4A

**Comment by EdwardLangdon** [comment]
You mean this - https://mymaps.google.com/ ?

If yes, This is definitely a bug. We will fix this in v2.2.

**Comment by ManeraKai** [comment]
This page gets redirect to https://www.google.com/maps/d/, that's why it's gets redirected
![image](https://user-images.githubusercontent.com/40805353/173162804-b3446dbb-f73e-4f90-a76c-ae6dc63211da.png)
I suggest closing off the maps toggle in the popup before dealing with anything related to google maps so no sub requests will be redirected wrongly.

**Comment by ManeraKai** [comment]
it's google maps:
![image](https://user-images.githubusercontent.com/40805353/173163318-688a7e3b-f9c3-40e5-b7df-646692a9b4a6.png)

**Comment by ManeraKai** [comment]
problem with OSM redirection is that it's not an alternative frontend rather a whole different web app and the features differ a lot between them. idk if someone didn't find the feature in OSM, then he should disable it all together imo.

**Comment by ManeraKai** [comment]
There's an exception setting in the general tab in the settings page. But it's the same way when someone wants to use twitter: toggle twitter redirections off, tweet a tweet, then toggle it back on.
