### ISSUE TITLE
Faq.html explains all permissions except for the newly added `privacy`

### ISSUE THREAD

**Issue by arty-name** [libredirect/libredirect#330]
As discussed here https://github.com/libredirect/libredirect/issues/291#issuecomment-1152196845, starting with 2.1 LibRedirect requests a new permission `privacy`. Reasons for all other permissions are listed in the FAQ, but not for this one.

**Comment by EdwardLangdon** [comment]
Issues regarding site should be asked here : https://github.com/libredirect/libredirect.github.io

Sorry don't get furious. The website will updated within few hours by me. Please wait.

Thank you.

**Comment by arty-name** [comment]
I wanted to ask it there, but the issues section is closed there :shrug:

**Comment by EdwardLangdon** [comment]
Oh, I see.

**Comment by EdwardLangdon** [comment]
@arty-name I have opened a PR updating the site : https://github.com/libredirect/libredirect.github.io/pull/10. This will be merged sooner.

Regarding issues not available, it was disabled because it's just a repo for website and static one. We will update sooner as soon as we do finish things.

I am just a collaborator helping ManeraKai in managing issues and some PRs with my knowledge in Free time.

I don't have top-level/write access to merge the PR. Please be patient.

**Comment by arty-name** [comment]
I am sorry if I left an impression that I try to rush things, or if the average newcomers to this repository are like that.

I just created a ticket for this issue, and I am truly impressed by the response speed! Thank you for addressing my feedback so quickly!
