### ISSUE TITLE
(invidious) do not redirects when the video is not yet available

### ISSUE THREAD

**Issue by iTrooz** [libredirect/libredirect#342]
The "Auto Redirect of offline instances" functionality auto-redirect you when you try to watch a video that has not been published yet. that cause an infinite loop of redirections

The example I tried to watch : https://invidious.esmailelbob.xyz/watch?v=RH5-F926Z0M

**Comment by EdwardLangdon** [comment]
The Video will premiere in 2 Days. For Premiere's both Piped and Invidious shows Error page as below

![image](https://user-images.githubusercontent.com/101938856/173999673-62aa0469-6a33-4940-8661-58ea1960163d.png)

![image](https://user-images.githubusercontent.com/101938856/173999496-0609c3ba-3d13-4eee-b89b-7f813cf7d629.png)

The reason that Invidious was stuck in a loop is because it shows an Error : premier in 2 Days. So, It's stucks in a loop. But actually we made the loop to stop after 5 redirects for 5xx errors not this type of errors.

The reason that Piped doesn't stuck in a loop is it gives a proper error message internally.

![image](https://user-images.githubusercontent.com/101938856/173999421-9c36ef6c-bd66-45cf-a634-7aa0e3d85761.png)

But We need to fix the Loop problem at set it to a certain threshold such as 10 and need to fix the HTML.

What do you think, Kai ?

**Comment by ManeraKai** [comment]
Well why invidious gives a 500 error?
![image](https://user-images.githubusercontent.com/40805353/174011703-df9c4938-54e7-4ed1-8951-b6ffa8b230eb.png)

**Comment by ManeraKai** [comment]
LibRedirect detects 500+ errors and auto redirects.

**Comment by ManeraKai** [comment]
I'll close this issue as it should be solved in invidious' side.
