### ISSUE TITLE
Add Imgur Redirection Support

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [libredirect/libredirect#36]
There are 3 Imgur privacy-respecting front-ends out there: 
- [Rimgo](https://codeberg.org/video-prize-ranch/rimgo) (Based on Rimgu)
- [Rimgu](https://codeberg.org/3np/rimgu)
- [Imgin](https://git.voidnet.tech/kev/imgin). 

They also have some public instances (official/unofficial). Adding this feature would be appreciated.

**Comment by ManeraKai** [comment]
Till now we've added Rimgo.

**Comment by EdwardLangdon** [comment]
We have decided not to add Imgin and Rimgu. Because, There seems to be no Public Instance of Rimgu. And Rimgo - A fork based on Rimgu is good and seems to be well maintained with a Decent list of Instances.

In the case of Imgin there is only one Instance - https://imgin.voidnet.tech/. It lacks features such as playing GIFs, Videos and has Stats such as No of views, Likes. Date/Time of Post. Support of User Profiles, Tags, Comments, etc. Which Rimgo does provide. 

So, Adding the other two would be waste of resources for us. I hope you understand the point here.

**Comment by ManeraKai** [comment]
Though if they got more support and more features. We'll add them.
