### ISSUE TITLE
Support for Pastebin

### ISSUE THREAD

**Issue by Heyya321** [libredirect/libredirect#374]
Pastebin Support with https://pastebinp.com or more i don't know other PB. proxy or instance things.

**Comment by MariojGG** [comment]
https://privatebin.info/

**Comment by MariojGG** [comment]
> > https://privatebin.info/
> 
> its a text cloud service just like pastebin and not related with pastebin
> 
> nah

https://pastebinp.com is not even open source there are better alternatives like https://github.com/beucismis/pastewin or https://privatebin.info .
And privatebin is not "like pastebin" because it is open source and encrypted, as well as being recommended by privacyguides. https://www.privacyguides.org/productivity/#paste-services.

**Comment by ManeraKai** [comment]
There's just one instance of pastebin proxy and the same for pastewin. I can't add them.

**Comment by ManeraKai** [comment]
If one of them got more instances and more notice, we'll add it.
