### ISSUE TITLE
TikTok redirect doses not work

### ISSUE THREAD

**Issue by tio-trom** [libredirect/libredirect#396]
I've seen that for the past 1-2 weeks. Try to visit such a link https://www.tiktok.com/@stickyhand64/video/7118244609066683691 and it won't redirect. Not even the main url https://www.tiktok.com - it will not redirect.

These are my settings:
![2022-07-22_16-15](https://user-images.githubusercontent.com/38043315/180458204-1ad8ac5d-975a-4f06-a35e-0998ff7e1318.png)

**Comment by tio-trom** [comment]
> Have you cleaned up your settings? If not, that might be a good way to solve it.

You mean to reset the settings? I'd like not to because of the custom settings I've setup for other instances...

**Comment by EdwardLangdon** [comment]
@tio-trom Then Export your settings, reset it, Check if redirects work and re-import your settings.

If possible, While Importing, send the console logs, It might help.

**Comment by tio-trom** [comment]
Ok a reset fixed it. I see many times that Libredirect needs to reset the settings and such...maybe you guys can make it work more seamless :). So that updates won't break the extension. I appreciate the work you do!

**Comment by RunningDroid** [comment]
I'm not sure if there's a more recent bug for this issue but I'm experiencing this as well, except resetting the settings does not work.
People in similar issues for other sites have suggested testing if Redirector works (because CORS or something similar may be causing the issue) and Redirector does work for me.

Screenshot of console logs:
![2023-04-16T19:01:30,295999955-04:00](https://user-images.githubusercontent.com/486393/232348119-9ead14a7-de1c-4a75-99db-a67defc2b1e9.png)
