### ISSUE TITLE
Publish extension to chrome store

### ISSUE THREAD

**Issue by itsmeboy0** [libredirect/libredirect#45]
Continuation of https://github.com/libredirect/libredirect/issues/18.

**Comment by dtbj** [comment]
I am waiting for it
want to install it please do it if possible

**Comment by IronMaltese** [comment]
I also think it should be published on the chrome store, but the extension can be used on chrome by downloading it on GitHub and following the steps on the main page of this GitHub

**Comment by dtbj** [comment]
@IronMaltese I installed it, it's far more better than privacy redirect it's good one. Thanks to all amazing devs.

**Comment by ManeraKai** [comment]
> I am waiting for it want to install it please do it if possible

you can install it as a `.crx` file from the releases page.

**Comment by ManeraKai** [comment]
> I also think it should be published on the chrome store

I don't have a credit card as of right now. This is our problem.

**Comment by IronMaltese** [comment]
Are you able to use a prepaid card for the transaction and does it cost a lot to have an extension published?

**Comment by ManeraKai** [comment]
The cost is just 5 dollars. What is a prepaid card?

**Comment by IronMaltese** [comment]
You’re referring to the $5 web developer fee right?

**Comment by ManeraKai** [comment]
yep

**Comment by IronMaltese** [comment]
You can usually get a Visa card with money already on it at Walgreens or cvs

**Comment by ManeraKai** [comment]
?

**Comment by IronMaltese** [comment]
Maybe it’s different for where you live, but there should be a way for you to find a Visa card with money on it at a nearby store

**Comment by ManeraKai** [comment]
I live in turkey. I will wait for @alefvanoon to response on that as he didn't respond for a while.

**Comment by ManeraKai** [comment]
It's totally logical. It's to prevent scammers and bots in general. There's no monthly fee, just this to have a developer account.

**Comment by ManeraKai** [comment]
yep

**Comment by m77e4t** [comment]
I made a comment regarding it on PG discussion forum, before reading the reason here.

https://github.com/privacyguides/privacyguides.org/discussions/636#discussioncomment-2245238

Can you get someone from your family to do it for you, who has a credit/debit card and is above 18? The community might compensate you for the $5.

**Comment by ManeraKai** [comment]
My family scenario is a little bit complicated in the meant time. I can't explain it on public but no one has a credit/debit card right now.

**Comment by EricWM612** [comment]
If the $5 through a credit card is the current blocker, I could possibly help somehow. Easy enough for me to create a limited-spend card with most of my personal info unattached, and I'd love to support the project in some small way! ($5 is no issue for something this awesome)

**Comment by ManeraKai** [comment]
let me get into this. https://privacy.com helps creating disposable credit cards.

**Comment by ManeraKai** [comment]
?

**Comment by EricWM612** [comment]
Privacy.com needs a bank account or debit card to pull the funds from, so if you're good with that, then perfect! But if there are any problems, I'm still willing to do it

**Comment by ManeraKai** [comment]
I can't obtain a credit card. This is my only problem. I have some money in a Payoneer account from [TurboSquid](https://www.turbosquid.com/Search/Artists/ManeraKai) but it needs to be more than 100$ for me to be able to create a credit card out of it.

**Comment by EricWM612** [comment]
I'm sorry, I didn't quite follow - does that mean you have an option, or that it didn't work?

**Comment by ManeraKai** [comment]
I don't have 100$ on that account. It's not working.

**Comment by ManeraKai** [comment]
@EricWM612 Trying to run it on chromium. I didn't know that manifest v3 needs work. background scripts can't even be persistent all the time. I'm working on it.

**Comment by ManeraKai** [comment]
I'm facing now a problem of having `background.js` as a type `module`. I can't set it to be type of `module`.

**Comment by ManeraKai** [comment]
> I'm facing now a problem of having `background.js` as a type `module`. I can't set it to be type of `module`.

Fixed that problem. I now have to define `window`. Idk why

**Comment by ManeraKai** [comment]
Fixed every problem. All the fixes are on a different branch called [chrome](https://github.com/libredirect/libredirect/tree/chrome), but we're now on a deal breaker problem. Let me explain.

#### The problem
As what @SimonBrazell said here: https://github.com/SimonBrazell/privacy-redirect/pull/319#issuecomment-985895209
Redirecting and blocking urls is now so impossible to do with the `webRequest` function. If you take look at the `manifest.json` files of [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect/blob/master/src/manifest.json#L5), [uBlock Origin](https://github.com/gorhill/uBlock/blob/master/platform/chromium/manifest.json#L76), and [Redirector](https://github.com/einaregilsson/Redirector/blob/master/manifest.json#L2), you'll see that they all use `manifest v2`. I can't add nor publish a `manifest v2` to the chrome web store. Read the warning in this page: https://developer.chrome.com/docs/extensions/mv2/

#### Alternatives to `webRequest`?
Further reading and I saw an alternative that is [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/). It's syntax is a static one and is like a settings page for chrome to use rather than with `webRequest` where you had to pass the request to the extension and wait for it's JavaScript code to process to respond. ex: [Imgur redirect function](https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/imgur.js#L103-L119). There's a whole lot of difference between static settings and a whole language like JavaScript processing and understanding your input and giving you an output.

#### What to do?
The only solution is to stay on `manifest v2` rather than `manifest v3`. The extension will still work on chromium browsers, but it can't be in the chrome web store.
Thankfully there are other extension stores for chromium browsers like [Edge Add-ons](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home),  [Opera Addons](https://addons.opera.com/en/extensions/). You can install extensions from them to chrome.

Sorry to tell you that. I totally forgot about it and didn't know that Google started applying that law to it's new submissions.

**Comment by IronMaltese** [comment]
This really sucks :/ I wish brave made an add on store, that would solve all our problems

**Comment by ManeraKai** [comment]
@IronMaltese I wish that too.

**Comment by ManeraKai** [comment]
@EricWM612 Sorry, but I now have a registered dev account that is almost useless.

**Comment by EricWM612** [comment]
That's no problem! Hopefully you can use it for something in the future. But whatever works 😀

**Comment by ManeraKai** [comment]
At the End. The extension can't be on the chrome web store because of `manifest v3`. I'll publish the extension on edge and opera stores. I'll still include the `.crx` files in every release. And I'll close this issue.

**Comment by EricWM612** [comment]
That's unfortunate! I can't say I looked into the specifics of the issue, but I wonder how other tools are dealing with these changes. Hopefully not Chrome intentionally making it harder to manage your own content 🙁

**Comment by ManeraKai** [comment]
>  intentionally making it harder to manage your own content slightly_frowning_face

¯\\_(ツ)_/¯

> I wonder how other tools are dealing with these changes

Here's a picture saying that the chrome web store won't accept new updates from old extensions that are still using manifest v2 on January 2023
![image](https://user-images.githubusercontent.com/40805353/157282372-64598025-ba36-4c0b-a71e-cd0dcbd181d8.png)
I took it from this page: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

Bring some Popcorn for that day xD

**Comment by IronMaltese** [comment]
> Here's a picture saying that the chrome web store won't accept new updates from old extensions that are still using manifest v2 on January 2023

I didn't know MV2 extensions will be blocked altogether soon, this makes me wonder what brave, ublock and other chromium-related projects are planning to combat this, or if all hope is lost for chromium besides a fork

**Comment by itsmeboy0** [comment]
> The extension can't be on the chrome web store because of `manifest v3`.

That day is still far ahead, so as of now you can still release it to the Chrome store. What do you think will other extensions like uBlock Origin do when that day comes?

**Comment by ManeraKai** [comment]
@itsmeboy0  I told you to bring some Popcorn. I really think that as @IronMaltese said a fork will come out and you won't see uBlock Origin again on the chrome web store.

**Comment by ManeraKai** [comment]
@itsmeboy0  I told you to bring some Popcorn xD. I really think that as @IronMaltese said a fork will come out and you won't see uBlock Origin again on the chrome web store.

**Comment by fariszr** [comment]
> > Here's a picture saying that the chrome web store won't accept new updates from old extensions that are still using manifest v2 on January 2023
> 
> I didn't know MV2 extensions will be blocked altogether soon, this makes me wonder what brave, ublock and other chromium-related projects are planning to combat this, or if all hope is lost for chromium besides a fork

Brave will continue to support mv2

**Comment by ManeraKai** [comment]
All brave needs is a separate web store. Hopefully...

**Comment by fariszr** [comment]
Related issue
https://github.com/brave/brave-browser/issues/15187

**Comment by m77e4t** [comment]
Personally, I think all non-chrome chromium browsers like Opera, Vivaldi, Brave should come together to form a separate chromium extension store. All 3 companies will contribute same amount of work/money/resources for the store.

Opera and Edge currently have their own extension store. But it is just bare-bones of actual chrome web store. If all companies come together to create a separate one, it would be pretty good.

**Comment by unixfox** [comment]
@ManeraKai I still have a chrome extension that got created in 2020, I don't use it anymore and it's still public. I can repurpose it for you in order to upload libredirect to the chrome store.
Would you be interested?
Here is the extension: https://chrome.google.com/webstore/detail/overcast-community-notifi/enfdbjdkmgpfpnbnhgbhdihhoaielfga?hl=fr&authuser=0

**Comment by ManeraKai** [comment]
@unixfox It's just a matter of time then even updating the mv2 extensions won't be possible. This is not a reliable solution.

**Comment by unixfox** [comment]
> @unixfox It's just a matter of time then even updating the mv2 extensions won't be possible. This is not a reliable solution.

Mmh ok, I meant to say that at least libredirect, even an old version, would still exist on the chrome store.

**Comment by ManeraKai** [comment]
Sadly, chrome will STOP supporting mv2 and all of the extensions will just stop working. This is the last step of the transition and will happen in June2023 as the picture says:
![image](https://user-images.githubusercontent.com/40805353/157282372-64598025-ba36-4c0b-a71e-cd0dcbd181d8.png)
I took it from this page: https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

**Comment by ManeraKai** [comment]
You can't just not update chrome. There are many security updates. Don't worry though. I think maybe Brave will com up with something

**Comment by ManeraKai** [comment]
Thanks for trying to help @unixfox

**Comment by m77e4t** [comment]
Changing user agent to edge will not work. Microsoft's store likely uses api via javascript to cross-check that the browser making the request is actually edge or someone pretending it to be. Opera does the same stuff.

**Comment by m77e4t** [comment]
Opera add-on store??

The extension is on edge store, which is quite useful for Windows users. Will it be published on Opera add-on store along with edge? It will increase it's reach for users.

**Comment by m77e4t** [comment]
Meaning that you applied to them, but they still have to approve your extension? If so, then OK.

Also, you should publish the extension on palemoon web store. Considering that the extension is not on the chrome web store (which the biggest extension store out there), we should try to target all other extension store.

**Comment by ManeraKai** [comment]
idk if it will work on Pale Moon. Even uBlock Origin seems to have only "legacy" version on it.

**Comment by guest271314** [comment]
@ManeraKai

> It's syntax is a static one

See https://github.com/GoogleChrome/chrome-extensions-samples/issues/662#issuecomment-1096104546 for an example of dynamically setting rules using MV3 `declarativeNetRequest`.

**Comment by Julmik647** [comment]
It may be off-topic, but there is browser extension called [Crosspilot](https://crosspilot.io/) that allows to download Opera extensions on other Chromium-based browsers, so it can be used if this extension will be on Opera Addons.

**Comment by guest271314** [comment]
> Try asking someone who already paid for publishing Chrome extensions.

Why do that?

Just publish on GitHub. 

Unless you're trying to sell something?

**Comment by ManeraKai** [comment]
> See https://github.com/GoogleChrome/chrome-extensions-samples/issues/662#issuecomment-1096104546 for an example of dynamically setting rules using MV3 declarativeNetRequest.

See https://libredirect.github.io/faq.html#mv3

**Comment by guest271314** [comment]
> > See [GoogleChrome/chrome-extensions-samples#662 (comment)](https://github.com/GoogleChrome/chrome-extensions-samples/issues/662#issuecomment-1096104546) for an example of dynamically setting rules using MV3 declarativeNetRequest.
> 
> See https://libredirect.github.io/faq.html#mv3

I'm pretty sure updating to MV3 won't impact what you can and can't do with the extension. 

You can intercept all requests with `chrome.debugger` and using one of the CDP API's, such as Network.
