### ISSUE TITLE
Clicking a link to a Medium article in a Medium article doesn't redirect

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [libredirect/libredirect#450]
With Medium redirection enabled, clicking [this](https://medium.com/@0x84003239/ethcc-stole-our-200-tickets-bf0904b9354a) redirects to a Scribe instance. That article links to another Medium article (ctrl-f `SecondTicket Wave`) - clicking that link goes straight to medium.com, instead of redirecting to Scribe.

**Comment by ManeraKai** [comment]
from Hygna:
The reason this happens is because when you go to a medium link from scribe, it assumes it is because you went on the page and the frontend didn't provide you with the information you need, so lets to go to the original service (this is the case with most frontends). But I see that sometimes it doesn't make sense, especially if the page you are being sent to isn't the same article as before, just on medium instead of scribe. So I guess the plan for us is to check if the medium article (or page for all frontends) is the page you were just on with scribe, and not to redirect if that is the case, but also to redirect anyways if the two pages don't match. We were having a similar issue with piped since they don't substitute youtube links in some places such as comments, causing people to go to youtube.com when clicking those, and I don't think it would be reasonable for every private frontend to scan content of all pages for links that should be redirected (although that would benefit people not using libredirect or some other redirector), so we will go ahead and fix this.(edited)

**Comment by EdwardLangdon** [comment]
Resolved in v2.3
