### ISSUE TITLE
Consider not using the Libreddit list of instances anymore

### ISSUE THREAD

**Issue by Dyras** [libredirect/libredirect#460]
Hello! It would seem like Libreddit has been abandoned without as much as a word. The instance list is no longer being updated:

https://github.com/spikecodes/libreddit/issues/585
I've removed 12 instances a month ago, with no response whatsoever in that time:
https://github.com/spikecodes/libreddit/pull/570

There's a fork as a result of this, which may or may not be worth looking at:
https://github.com/spikecodes/libreddit/issues/594

With that said, I think at the very least we should make our own instance list instead of relying on the incredibly outdated list hosted by Libreddit at this point.

**Comment by EdwardLangdon** [comment]
@Dyras If you could keep a repo of Libreddit instances which is maintained and updated. It should be clean one and need to be checked at often cuz because of this unmaintained list, some of the users got redirected scammy instances as you listed and also one of the reason that made the extension to be unlisted from Microsoft Edge Store.

We will think of it, If it is up-to-date. Except Libreddit all others are maintainer.

I leave this decision to Kai.

**Comment by Dyras** [comment]
If you decide to keep a list of instances yourselves, I will guarantee you that I will make pull requests to remove the ones that go offline. I use Libreddit with Libredirect (I hate how similar the names are btw) and so I will notice almost instantly if one goes down.

Perhaps @Daniel-Valentine would consider making an up to date repo for the instances? Seeing as he's forked the project itself already.

**Comment by EdwardLangdon** [comment]
I think Daniel, 2nd step is better. Because we have it already and just need to change the URL to fetch stuff.

We won't be maintaining list separately (unless there is no proper Frontend URLs rather API only) because rewriting the extension with future in mind itself is taking time for us despite things IRL.

By the Way, It's pronounced as Lib-redirect some might confuse as Libre-redirect.

**Comment by EdwardLangdon** [comment]
Daniel, Whatever way repo or Readme, The regex just applies, IIRC.

But just keep instances that are only up-to-date.

P.S. create auto-updater script in the fork, So, Maintainers have up-to-date instance and have some burden down.
