### ISSUE TITLE
Can't Redirect Embedded YouTube Videos on Discord?

### ISSUE THREAD

**Issue by MintMain21** [libredirect/libredirect#484]
I could've sworn LibRedirect could do this before, but now it can't.

I realize this is what the "disable redirects for this tab" option is for, but I feel like it's worth reporting all the same.

**Comment by EdwardLangdon** [comment]
You might be right, Because as a user of discord I do also remember libredirect being able to replace embeds.

![image](https://user-images.githubusercontent.com/101938856/195764028-eeaffbc8-10c8-4f9d-97d7-8b002befd4e9.png)

As you see in the image above from Console Logs, Discord Web app now uses Content Security policy and defines what are the sites that can be inside the `iframe` of Discord. If it is not in the list, you cannot inject your own script to replace the embed.

So, If you want to replace embeds with Piped or Invidious, Then hack Discord's servers, Alter the CSP to accepts domains from both Piped & Invidious Instance list. Just kidding. 😁

We can't do anything to get over CSP. Because it is defined and only site owners can change it. Without that, There's nothing we can't do.

Sorry. Closing this issue.

Next time, Please add more info in your issue. Took some to recognize from description unless I read the title at last, lol.
