### ISSUE TITLE
Add version to About info

### ISSUE THREAD

**Issue by JediMaster25** [libredirect/libredirect#490]

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/196313575-397a9a63-762c-4ee5-a4a2-b720659493ed.png)

![image](https://user-images.githubusercontent.com/101938856/196313597-e6c5d91b-c6b9-4832-b026-e18c5ba54faa.png)

You can find the extension version in the browser itself. So, This seems unnecessary.

The About info is mainly made. So that users know where to contact us regarding issues, Bugs and to got to FAQs to understand things via Documentations.
