### ISSUE TITLE
Settings get reset on extension update

### ISSUE THREAD

**Issue by jamesWalker55** [libredirect/libredirect#500]
Whenever the LibRedirect extension is updated on Firefox, all my settings are erased. Sites I have disabled become enabled, and I have to manually check and fix the settings for each site.

I'm using Firefox 106.0.1.

**Comment by haluzpav** [comment]
Yes, now it happened for a second time in a few days...

**Comment by EdwardLangdon** [comment]
Does the settings are saved as is after fixing for yourself ?

If you mean all redirections being enabled even disabled. It's fixed in a latest commit. Maybe try if it fixes.



> Yes, now it happened for a second time in a few days...

It was settings not being saved. This is settings where being reset on update.

---

THe reason why we added Export/Import for Settings. So, You don't need to do over.

**Comment by BlepBlep** [comment]
For me, it wasn't the settings being changed, it was the redirections being re-enabled. I see that you mentioned it being fixed, which I'm excited about. Sick of opening YT and it not being YT randomly.

**Comment by EdwardLangdon** [comment]
This issue is a duplicate of #499.
