### ISSUE TITLE
Doesn't redirect at all in Vivaldi Windows or MacOS - Installs fine

### ISSUE THREAD

**Issue by bleomycin** [libredirect/libredirect#520]
Tried both installation methods in Vivaldi on Windows and MacOS. Extensions installs fine in both instances, using the "linux" and "windows/macos" methods listed. Extension appears to be working fine all settings available but it fails to redirect anything to anywhere. Happy to provide logs but no idea how.

**Comment by IkelAtomig** [comment]
I tested the extension in Vivalid in Windows. It just works fine.
For the specifics. Latest Vivaldi with Win11 22H2 using Windows Sandbox (I used the sandbox as I wanted to use it only for this issue). If it works there, there is no issue as it is naive and Stock Windows Experience. There is a problem in your device. Probably try reinstalling Vivaldi.

Try to use the Zip file rather than `crx`.

**Comment by Sapiosenses** [comment]
> I tested the extension in Vivalid in Windows. It just works fine. For the specifics. Latest Vivaldi with Win11 22H2 using Windows Sandbox (I used the sandbox as I wanted to use it only for this issue). If it works there, there is no issue as it is naive and Stock Windows Experience. There is a problem in your device. Probably try reinstalling Vivaldi.
> 
> Try to use the Zip file rather than `crx`.


Maybe it's intermittent on that platform.

For example I'm using LibreDirect in Vivaldi on macOS at the moment, and some domains are redirecting (eg Twitter, YT) but Instagram links seem to go directly to Instagram with no attempt to redirect at all. (No error about an instance not running or anything, it just goes right to Instagram. And I've already disabled all the obvious bibliogram instances since apparently that project is dead.)

**Comment by IkelAtomig** [comment]
As there are no instances selected. It won't try to redirect and only posts/reels are redirected not profiles.
