### ISSUE TITLE
Piped updated URLs

### ISSUE THREAD

**Issue by phoropter** [libredirect/libredirect#528]
Piped main instance URL is now https://piped.video along with new mirrors:
https://github.com/TeamPiped/Piped#mirrors

**Comment by IkelAtomig** [comment]
It will be updated by the Instance fetcher automatically we won't interfere it. See the FAQ page - https://libredirect.github.io/faq.html#where_the_hell_are_those_instances_coming_from.

Please wait till the fetcher updates instance list.

Next fetching will be on tomorrow. We will try to run manually before that so that. By the way, the Old Main instance is still active and won't be going anytime soon. So try updating the instances list this weekend.

The Proxy is for a reason to access when you can't access anything. So, we won't add it unless in the instance.

I am closing this issue.
