### ISSUE TITLE
Remove twitter query string

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/libredirect#532]
Remove ?s=19, ?s=20, ?ref_src=twsrc^tfw or any other parameters and replace with #m (the tweet will be focused if it is in a thread)

#r which is jump to replies, otherwise I don't know

**Comment by AlyoshaVasilieva** [comment]
`ref_src` and `ref_url` are already deleted:

https://github.com/libredirect/libredirect/blob/01a9a55f7d1dae2469ee7f933081d065325225b1/src/assets/javascripts/services.js#L153-L157

I think the remaining Twitter tracking parameter is `t` (originating from the share function, probably an encoded ID of your Twitter account). I don't know of any actually useful Twitter query parameters for tweets, but LibRedirect can redirect Twitter searches and removing all query params would break this (since the query is the param `q`)

Adding `#m` sounds great since currently being redirected into a thread/reply will drop you at the top of the page, not the focused tweet

**Comment by ManeraKai** [comment]
So... remove `s`, `ref_src`, `t` and put `#m`?? This is confusing :'D

**Comment by IkelAtomig** [comment]
A lot.

**Comment by ManeraKai** [comment]
If so then I won't play with them till they are clarified, and nitter instances already don't know them either so.

**Comment by AlyoshaVasilieva** [comment]
1. Remove `s` (useless, tracking, but low entropy)
2. Remove `ref_src` (already done, tracking)
3. Remove `ref_url` (already done, tracking, not encrypted so a malicious instance could monitor it)
4. Remove `t` (useless, tracking?, encrypted? so only Twitter knows what this is)
5. Add `#m` to statuses because it focuses the tweet, otherwise the browser starts at the top of the page (even if the linked tweet is deep in a thread)
