### ISSUE TITLE
Ability to redirect search engine pages (Google, Bing, DDG, Brave, Startpage, etc.) to meta search engine frontends (SearX/NG, Whoogle, LibreX, etc.)

### ISSUE THREAD

**Issue by SkMyPP** [libredirect/libredirect#583]
It doesn't make any sense that LibRedirect doesn't redirect google.com, bing.com, duckduckgo.com, search.brave.com & startpage.com to meta search engines like it does for twitter.com to nitter.net or youtube.com to yewtu.be

**Comment by ManeraKai** [comment]
Read the `Bad Examples` => `Startpage` part in the FAQ: https://libredirect.codeberg.page/faq.html#suggest_frontend

**Comment by SkMyPP** [comment]
That is such an asinine point of view. By that logic, YouTube doesn't need any redirections because I can just set an Invidious instance as an alternative search engine in the address bar ¯\_(ツ)_/¯

What I'm saying is to redirect google.com, duckduckgo.com, bing.com, startpage.com, search.brave.com, etc to the meta search engine of my choosing. That's what LibRedirect is meant to do. If it does it with YouTube and Twitter, it should go without saying that it should do the same for google.com & every other search engine like it.

**Comment by ManeraKai** [comment]
Here are some points:
- YouTube is a lot different since it's not a search engine, many people share videos to each other or you see youtube links on the internet and that requires automatic redirection.
- No one gives or shares you a duckduckgo.com link, it's so rare for anyone to do that. So no need for automatic redirection and wasting resources
- Startpage.com for example isn't a default search engine. So in theory, you should first install it and make it the default search engine, then after that use LR to redirect from it to SearXNG for example, which is totally illogical and unneeded.
- google.com's homepage isn't just a search engine, it has other buttons to access other google services.
- Yahoo and Google have "image search" features that the user wanna use, but he can't now bc we're redirecting those links to SearXNG with doesn't support image search.

This was a long decision and we already thought of it deeply.

**Comment by ManeraKai** [comment]
And yes I will remove that `¯\_(ツ)_/¯` bc it's teasing some people apparently xD

**Comment by SkMyPP** [comment]
Here are some other points:

-  YouTube _is_ a search engine. In fact, it's the second largest search engine in the world (after Google). 
- Your assumption that no one shares search engine links is purely anecdotal. And besides, you can get redirected to google.com or bing.com without ever wanting to. A good example is browsers resetting the default search engines.
- Your point of "no need for automatic redirection and wasting resources can be said for about 80% of the redirections LibRedirect lists.
- Startpage is a terrible search engine, so no one should be installing their awful addon to default into it.
- If you're someone that cares about online privacy, you wouldn't even be using LibRedirect in the first place. Much less any of Google's awful services.  Plus, it's something that you can add an exception for in the add-on so it's a moot point anyway.
- SearXNG isn't the only meta search engine that exists, that point is also moot.

Clearly it was a half-baked idea to add searches as an option in LibRedirect because it's only useful if you add it as an alternative search engine, something you can already do with literally any other search engine. So it's kinda dumb to enable that option when you can add any other meta search engine as an alternative search engine in the address bar.

Maybe just remove the search option since it serves absolutely no purpose in the first place ¯ \ (ツ) / ¯

**Comment by ManeraKai** [comment]
> YouTube is a search engine. In fact, it's the second largest search engine in the world (after Google).

What I'm meaning is that no one puts it as the "Default Search Engine" on their address bar. That's what I'm meaning by search engine.

> And besides, you can get redirected to google.com or bing.com without ever wanting to. A good example is browsers resetting the default search engines.

This accidental thing isn't worth it to make libredirect redirect those urls too.

> Your point of "no need for automatic redirection and wasting resources can be said for about 80% of the redirections LibRedirect lists.

It's really hard to decide and arguments are always happening about to add/remove a frontend or not. We're trying to balance everything out.

> Startpage is a terrible search engine, so no one should be installing their awful addon to default into it.

I just gave it as an example bc some people also wanted me to redirect Ecosia which is literally not a default search engine on ANY browser and no one uses it without his consent first unlike default search engines. That's what I was meaning.

> If you're someone that cares about online privacy, you wouldn't even be using LibRedirect in the first place.

It's a simple tool for beginners to enter the privacy world in an easy way, more advanced people would use Redirector or other extensions or not use frontends at all.

> Much less any of Google's awful services.

It's about necessity, google ofc has important services.

>  Plus, it's something that you can add an exception for in the add-on so it's a moot point anyway.

It was like that before, having google.com's home page not redirected, but redirect when you press enter to search. This was previously on Privacy Redirect, and safe to say it was a terrible idea. We removed it at the end.

> SearXNG isn't the only meta search engine that exists, that point is also moot.

I'm just using it as an example don't worry.

> Clearly it was a half-baked idea to add searches as an option in LibRedirect because it's only useful if you add it as an alternative search engine, something you can already do with literally any other search engine. So it's kinda dumb to enable that option when you can add any other meta search engine as an alternative search engine in the address bar.

> Maybe just remove the search option since it serves absolutely no purpose in the first place ¯ \ (ツ) / ¯

The main reason we added it that you can't do with searXNG or any other meta search engine's page alone is that you can use multiple instances at the same time with LibRedirect. Otherwise you can right click on the address bar of any searXNG instance and "Add SearXNG"

**Comment by SkMyPP** [comment]
I'm not reading all of that. 

As it stands the "Search" option in LibRedirect is a half-baked idea that serves no functional purpose.
