### ISSUE TITLE
Why was Wikiless removed?

### ISSUE THREAD

**Issue by mojo-jojo-7** [libredirect/libredirect#604]
Just curious to know the reason for the removal of Wikiless (and also Neuters). Could not find an existing issue related to this

**Comment by IkelAtomig** [comment]
Reason for removal of Wikiless - https://github.com/libredirect/libredirect/issues/606#issuecomment-1409463740

For Neuters, I was the one who proposed to remove it since you can block all trackers using uBO or Adguard. Assuming that people using Libredirect will probably use Adblocking. Reuters is a general news site. So, Not a major reason to have though.

Even though, if we are gonna have neuters, The only Official instance is a Demo instance and nothing else. Which could go down anytime.

**Comment by HookedBehemoth** [comment]
Sure

**Comment by shruuub** [comment]
> For Neuters, I was the one who proposed to remove it since you can block all trackers using uBO or Adguard. Assuming that people using Libredirect will probably use Adblocking. Reuters is a general news site. So, Not a major reason to have though.

You can also block all trackers on reddit, youtube or twitter, there is more to using a frontend then just saying that one should use an adblocker (which should be done regardless)

**Comment by adastx** [comment]
Regarding something like Neuters, I think it is important to note that some people may value minimal frontends over their bloated originals. 

A more concrete case could be if you have a limited data plan.

This is one of neuters key feauters in their 'about' page:
> Lightweight (usually <10KiB vs 50MiB from Reuters)

I didn't personally use neuters, but it's worth considering frontends for privacy (and/or) minimalism.

**Comment by IkelAtomig** [comment]
Fine Fine. We will open a issue if we are going to remove one.
