### ISSUE TITLE
Instance addition/change for non-cloudflare official kavin.rocks

### ISSUE THREAD

**Issue by Kostrol** [libredirect/libredirect#614]
- [ ] Change one instance of https://piped.video/ [cloudflare](https://libredirect.github.io/docs.html#instances) **->** [piped.video libre](https://pipedapi-libre.kavin.rocks) non CDN version. 

Current (double listed) piped.video instances of are both tagged cloudflare in libredirect, however Piped has a claimed non-cloudflare version of kavin.rocks here. https://pipedapi-libre.kavin.rocks/ https://github.com/TeamPiped/Piped/wiki/Instances

I have already favorited this instance myself, but think this should be natively implemented within the instance lists for PSA and security.

**Comment by ManeraKai** [comment]
Well bc it's redirecting to piped.video every time I try opening it.

**Comment by ManeraKai** [comment]
pipedproxy-ams-2.kavin.rocks is behind cloudlfare

> So I guess they are actually just straight up lying..? Very unfortunate.

No I think there's a misconfiguration or something.

@FireMasterK

**Comment by FireMasterK** [comment]
> pipedproxy-ams-2.kavin.rocks is behind cloudlfare
> 
> > So I guess they are actually just straight up lying..? Very unfortunate.
> 
> No I think there's a misconfiguration or something.
> 
> @FireMasterK

It's not behind Cloudflare. The IP simply isn't even Cloudflare.

![image](https://user-images.githubusercontent.com/20838718/216667152-52b6a25f-ac1e-4245-b1f8-ed826bc16612.png)
![image](https://user-images.githubusercontent.com/20838718/216667257-7c7c0efc-3be2-4c7e-a306-67e20f0fbbd9.png)

**Comment by ManeraKai** [comment]
> It's not behind Cloudflare. The IP simply isn't even Cloudflare.

Right, sorry.

**Comment by FireMasterK** [comment]
The problem is Libredirect doesn't have a proper understanding of Piped's API, but instead tries to redirect to a frontend of Piped.

The thing is each frontend instance of Piped is designed to be able to connect to any API instance of Piped. For example, you can can go to https://piped.video/preferences and switch instances in the bottom of the page. This is the official and recommended way to use Piped, since frontends could be potentially modified by instance operators in a harmful manner, and there's no way to check the frontend's code.

The Piped frontend is also available through a few other officially hosted means, such as IPFS, Tor, and a few Clearweb mirrors.

What I'd recommend libredirect to do, is allow choosing a frontend and backend independently. (You can set the backend independently through localstorage)

**Comment by ManeraKai** [comment]
> The thing is each frontend instance of Piped is designed to be able to connect to any API instance of Piped. For example, you can can go to https://piped.video/preferences and switch instances in the bottom of the page. This is the official and recommended way to use Piped, since frontends could be potentially modified by instance operators in a harmful 

I know this, but people wanted it to be like that anyway.

> The Piped frontend is also available through a few other officially hosted means, such as IPFS, Tor, and a few Clearweb mirrors.

Didn't know it's on IPFS too, interesting.

> What I'd recommend libredirect to do, is allow choosing a frontend and backend independently. (You can set the backend independently through localstorage)

I will see what I can do.
