### ISSUE TITLE
[Feature Request] Add "Toggle libredirect on this tab" in left click menu

### ISSUE THREAD

**Issue by Ridhubharan** [libredirect/libredirect#640]
Add "Toggle libredirect on this tab" in left click menu. It was present in previous versions but not available anymore.

**Comment by ManeraKai** [comment]
You'll see it in the next version:
![image](https://user-images.githubusercontent.com/40805353/222975442-a877e66c-119e-42dd-afd5-fb6d8eb3b9c1.png)

**Comment by Ridhubharan** [comment]
@ManeraKai These options are only available when i click on a link. It will be better if these options can be accessed when right-clicked on empty space and the current page is redirected.

**Comment by ManeraKai** [comment]
You can do so by right clicking on the LibRedirect icon.

**Comment by Terkyz** [comment]
Is there any chance that this will be re-integrated in LibRedirect in future releases?

**Comment by ManeraKai** [comment]
It is already?

**Comment by Terkyz** [comment]
At least in my case [it's not like that](https://i.imgur.com/iylKWq5.jpg), and I'm on LibRedirect 2.6.2.

**Comment by ManeraKai** [comment]
In the picture I was right clicking the "YouTube" word (it's actually a link). Right click the LibRedirect icon:
![image](https://github.com/libredirect/browser_extension/assets/40805353/32bb16dc-54af-47d5-9898-7d417830cffd)

**Comment by Terkyz** [comment]
I already tried it and it works as it should, both pressing on the LibRedirect icon and pressing right click on a direct link, but I remember that for example. if I'm on Youtube and right click anywhere on the screen the LibRedirect icon along with its actions (Redirect, Redirect to Original, Copy Original) allowed me to redirect to an instance of Invidious just by clicking on one of its options in that right click submenu, I didn't need to go to the extension symbol, which I find a bit more convenient than having to go to the corner of the screen to do the same thing.

This is not a feature request, it is a comment, after all this function is already implemented and I could use it using shortcuts if I wanted convenience, I was just commenting because I remembered this function.
