### ISSUE TITLE
Removing Favorite Instances Causes Unknown Host

### ISSUE THREAD

**Issue by harvest316** [libredirect/libredirect#659]
When all favorites are removed, searching causes an "unknown host" error.

### Steps to replicate:
1. Go to the Search tab in Libredirect Settings on Firefox
2. Under "Add your favorite instances" click X to remove all favorites
3. With Libredirect set as the default search engine, search for the word "test"

### Expected result:
* We would be redirected to a random search engine from the list downloaded from Github/Codeberg

### Actual result:
* We're stuck on the URL https://search.libredirect.invalid/?q=test
* It is not redirecting to a search engine as it should
* The displayed error is "Hmm. We’re having trouble finding that site. We can’t connect to the server at search.libredirect.invalid." 
* The Network tab of the Browser Console shows the underlying error to be NS_ERROR_UNKNOWN_HOST

### Proposed Change:
I do not want to use the same few instances all the time (this creates a footprint I'd prefer avoid).  A more secure default configuration is to not have any favorite instances, and therefore randomly select one of the many instances pulled from Github/Codeberg.  At very least, I'd like to see an "Add All" button to mark all instances as favorites.

**Comment by ManeraKai** [comment]
> Expected result:
We would be redirected to a random search engine from the list downloaded from Github/Codeberg

If you went to YouTube and removed all favorite instances, the same will happen, it will open youtube.com normally. It's just that search.libredirect.invalid isn't an actual url this happens. And the list that is downloaded from Github/Codeberg isn't cached. It downloaded every time you open the settings page, so selecting a random instance isn't an option.

**Comment by harvest316** [comment]
Thanks for explaining, @ManeraKai 

In that case, what's the chance we can have an "Add All" button to mark all instances as favorites?

**Comment by ManeraKai** [comment]
This option was their before but got removed bc the custom list that you make now is completely independent of the fetched list.

**Comment by harvest316** [comment]
I understand that is how it is, but it feels like we took a step backwards.

My understanding is that the primary purpose of libredirect is privacy.  One of the easiest ways to do this is to scatter our searches through a wide range of different proxy services such as SearxNG, Proxitok, etc, and the wider that range, the better.  This primary use-case for me was happily satisfied by the previous way that libredirect worked.  But now, to satisfy the same use-case involves clicking on every fetched service to add it to my favorites, and regularly repeating this process to add any new services to my favourites list.

Ideally, I'd like a simple switch that toggles between "randomly select from all fetched services" and "randomly select from the following favorite services".  But at very least, can you bring back the button to add all fetched engines to favorites?

**Comment by ManeraKai** [comment]
You are right about what you said. It's becoming a problem really.
The problem is you can apply this "randomizing" to just some frontends, but not all of them. For example this can be beautifully done with SimplyTranslate, in fact my own client simplytranslate_mobile does exactly that.
But then you come to Invidious of Piped, they should have a "subscription list", now if I want to "randomize my selection" then I either should have an account for every single invidious instance, or I should have my subscription stored in localStorage for every single Piped instance. This id the problem, I'm now sharing my subscription to ALL instances.
I still didn't even talk about how using random instances with their "web interfaces" is so dangerous to privacy bc you don't know what JavaScript they have. With "clients" like simplytranslate_mobile or LibreTube this threat isn't their bc you are using your own interface that you coded in Android rather than the instance's web interface that it sends you.
There should be a solution to all this.

**Comment by harvest316** [comment]
Oh my, I see the complexity there!

But I like the solution you hinted at there.  We need a "randomizing" switch so we can set say Invidious to just randomize among a preferred subset of favourite proxies, and set SearxNG to randomize among the full set published on Github.  "Randomly redirect to favorites" vs "Randomly redirect to all"

Thanks @ManeraKai 

BTW, Libredirect is my favorite plugin by far. :)

**Comment by harvest316** [comment]
Hi @ManeraKai 

I just had a further improvement to this idea.  After running the latency ping, provide a button to add all green-ping servers to favorites.  Hope it helps.

**Comment by ManeraKai** [comment]
You will understand my point better, I creates this new repository that is solving this issue: https://github.com/libredirect/frontends_manager
