### ISSUE TITLE
Button to temporary disable redirect

### ISSUE THREAD

**Issue by trymeouteh** [libredirect/libredirect#73]
Please add a button which can be pressed which will temporary disable all redirects for 30 seconds.

**Comment by ManeraKai** [comment]
Can't I add a toggle all switch?

**Comment by trymeouteh** [comment]
This request is to disable redirects for a short period of time. The benefit of a temporary button is that you will not need to worry about forgetting to enable the redirects. A toggle switch can work but the user may forget to enable it again after 30 seconds or so and still be directed to proprietary sites forgetting about the redirect being turned off.

**Comment by ManeraKai** [comment]
Sorry but still not convinced. I don't want to have more buttons in the popup since the space is already being taken. I may add just the critical most important ones. The usage for a `toggle all` button is more practical and doesn't strict the user in time. The user should have the freedom to disable and enable the redirections whenever he wants.
