### ISSUE TITLE
Redirect pixiv.net to pixiv.moe

### ISSUE THREAD

**Issue by tusooa** [libredirect/libredirect#84]
`https://www.pixiv.net/en/artworks/{id}` -> `https://pixiv.moe/illust/{id}`
`https://www.pixiv.net/artworks/{id}` -> `https://pixiv.moe/illust/{id}`

`pixiv.moe`: https://github.com/kokororin/pixiv.moe

## upstream
https://github.com/SimonBrazell/privacy-redirect/issues/363

**Comment by ManeraKai** [comment]
Added it. The README has a [guide](https://github.com/libredirect/libredirect#development) on how to run the extension from the source code.

**Comment by whatbh** [comment]
I appreciate the effort of both requester and maintainer. But here's just my opinion: at some points we may need to draw a line on what's going to be added to avoid becoming a scope hell. Unless reasonably the frontend is privacy-centric and the backend is privacy-abusing, let's recall that we had plenty of "redirector" add-ons and scripts already, this Libredirect should be in focus of privacy.

**Comment by ManeraKai** [comment]
@whatbh You're right.

> Unless reasonably the frontend is privacy-centric and the backend is privacy-abusing

@tusooa do you have anything to say about his?

**Comment by tusooa** [comment]
> 

pixiv.net requires authentication for many operations like downloading full size image, pixiv.moe does not have this restriction.

**Comment by ManeraKai** [comment]
There is google-analytics on the site.

**Comment by whatbh** [comment]
Definitely a deal breaker. We good 👍

**Comment by ManeraKai** [comment]
@tusooa If you really want an automatic way to redirect those links. I'll try to write for you a custom setting for [Redirector](https://einaregilsson.com/redirector/).

**Comment by IronMaltese** [comment]
> at some points we may need to draw a line on what's going to be added to avoid becoming a scope hell.

I feel like this problem shouldn't come at the cost of limiting what redirections should be added (I'm not commenting on the pixiv redirection since I don't use it) I believe that this problem should be solved with a UI change, since the design of listing every site redirect when clicking the extension is destined for clutter, there are many possible solutions, but mine are to add a search bar at the top that allows the user to search which site to redirect (this shouldn't be implemented now, but when clutter starts appearing this might be necessary) and maybe even get rid of the whole idea of the list existing outside extension settings and add a button saying "disable redirects for (the current site)" feel free to criticize these ideas

**Comment by IronMaltese** [comment]
Maybe even put the settings for the site when the browser extension is clicked, Ex (User can make invidious instances 720p by default just by clicking the extension in the top bar) and the top of those settings can have YouTube with the yellow check next to it, and if you disable the yellow check, it'll bring you back to YouTube this will effectively serve the same purpose as the current design because users would be able to turn off the redirect after they're redirected, then go back to the main site

**Comment by IronMaltese** [comment]
Should I create a separate issue for this?

**Comment by ManeraKai** [comment]
I like your idea, I'll keep pixiv but disable it by default and give a warning as this is not a fully privacy redirection. The extension name isn't PRIVACY redirect but rather just Libre redirect. `pixiv.moe` is a better option for privacy than `pixiv.net` but not a fully privacy one like Nitter.

For the popup redesign, I agree with you about it, but the UI design are out of the scope, so as you said opening another issue for the design is better. I'll keep pixiv but disable it by default and add a warning as not a fully privacy oriented redirection.

**Comment by IronMaltese** [comment]
I'll open to discuss ways to reduce clutter in the extension tomorrow, but the warning should be added to mobile Reddit and old Reddit as well as pixiv

**Comment by ManeraKai** [comment]
Mobile Reddit isn't implemented as a redirect service, but I'll add the warning to Old Reddit and Pixiv as sometimes you can't have a better option.

**Comment by ManeraKai** [comment]
Like this?
![image](https://user-images.githubusercontent.com/40805353/157480167-eab1f85d-ccc4-4fcd-9093-4338d1bcbfb1.png)
Does anyone have a better warning sentence if you didn't like this one?

**Comment by ManeraKai** [comment]
Added a customize popup option in the settings:
![image](https://user-images.githubusercontent.com/40805353/157503982-5de8f3ed-12b7-4b15-ab4a-2c82e83a03dd.png)
Pixiv is disabled by default as there's no alternative frontend other than PixivMoe. I'll now close this issue. @tusooa if you have any problems with the implementation, just write it here 👍

**Comment by IronMaltese** [comment]
The English is a bit off, "This isn't a fully private frontend" is a better sentence
